components:
  schemas:
    P1Config:
      properties:
        dhgroup:
          $ref: ../dhp1group/dhp1group.yaml#/components/schemas/DhP1Group
          x-field-uid: 1
        encalgorithm:
          $ref: ../encp1algorithm/encp1algorithm.yaml#/components/schemas/EncP1Algorithm
          x-field-uid: 2
        hashalgorithm:
          $ref: ../hashp1algorithm/hashp1algorithm.yaml#/components/schemas/HashP1Algorithm
          x-field-uid: 3
        initialcontact:
          type: boolean
          x-field-uid: 4
        lifetime:
          format: int32
          type: integer
          x-field-uid: 5
        prfalgorithm:
          $ref: ../prfp1algorithm/prfp1algorithm.yaml#/components/schemas/PrfP1Algorithm
          x-field-uid: 6
      required:
      - lifetime
      - encalgorithm
      - hashalgorithm
      - dhgroup
      - prfalgorithm
      - initialcontact
      type: object
