components:
  schemas:
    TunnelSettings:
      properties:
        authsettings:
          $ref: ../authsettings/authsettings.yaml#/components/schemas/AuthSettings
          x-field-uid: 1
        outertcpprofile:
          $ref: ../tcp/tcp.yaml#/components/schemas/tcp
          x-field-uid: 2
      type: object
