components:
  schemas:
    TunnelSettings:
      properties:
        authsettings:
          $ref: ../authsettings/authsettings.yaml#/components/schemas/AuthSettings
          x-field-uid: 1
        links:
          items:
            $ref: ../apilink/apilink.yaml#/components/schemas/APILink
          type: array
          x-field-uid: 3
        outertcpprofile:
          $ref: ../tcpprofile/tcpprofile.yaml#/components/schemas/TcpProfile
          x-field-uid: 2
      type: object
