components:
  schemas:
    Params:
      properties:
        arrayelements:
          items:
            $ref: '#/components/schemas/Params.Arrayelements'
          type: array
          x-field-uid: 2
        arrayelementtype:
          description: The type of the array elements.
          type: string
          x-field-uid: 1
        category:
          description: The category associated with the parameter
          type: string
          x-field-uid: 3
        categoryindex:
          description: The position of the category in the category list
          type: integer
          x-field-uid: 4
        deprecatedprevioussource:
          description: A value indicating that this parameter had a source that was
            deprecated
          type: string
          x-field-uid: 5
        description:
          description: The description of the parameter
          type: string
          x-field-uid: 6
        dictionaryvalue:
          $ref: '#/components/schemas/Params.Dictionaryvalue'
          description: The dictionary value of the parameter.
          x-field-uid: 7
        enum_property:
          $ref: '#/components/schemas/Params.Enum_property'
          x-field-uid: 8
        file_upload:
          items:
            format: byte
            type: string
          type: array
          x-field-uid: 22
        filevalue:
          $ref: ../filevalue/filevalue.yaml#/components/schemas/FileValue
          x-field-uid: 9
        flowidentifier:
          description: If true, the value of this parameter is used to uniquely identify
            an application/attack
          type: boolean
          x-field-uid: 10
        isdeprecated:
          default: false
          type: boolean
          x-field-uid: 11
        ismodified:
          type: boolean
          x-field-uid: 12
        mediafiles:
          items:
            $ref: ../mediafile/mediafile.yaml#/components/schemas/MediaFile
          type: array
          x-field-uid: 13
        # metadata:
        #   $ref: ../parammetadata/parammetadata.yaml#/components/schemas/ParamMetadata
        #   x-field-uid: 14
        name:
          description: The name of the parameter.
          type: string
          x-field-uid: 15
        paramid:
          description: The id of the parameter.
          type: string
          x-field-uid: 16
        readonly:
          type: boolean
          x-field-uid: 17
        source:
          description: The source of the parameter.
          type: string
          x-field-uid: 18
        supportedsources:
          description: A list that indicates possible sources for the parameter
          items:
            type: string
          type: array
          x-field-uid: 19
        supportsdynamicpayload:
          description: A value that indicates if the parameter can have dynamic payload.
          type: boolean
          x-field-uid: 25
        type:
          description: The type of the parameter.
          type: string
          x-field-uid: 20
        uploadurl:
          description: The URL where the file parameter content could be uploaded.
          type: string
          x-field-uid: 26
        value:
          description: The value of the parameter.
          type: string
          x-field-uid: 21
      type: object
    Params.Arrayelements:
      properties:
        additionalproperties:
          type: string
          x-field-uid: 1
      type: object
    Params.Dictionaryvalue:
      properties:
        additionalproperties:
          type: string
          x-field-uid: 1
      type: object
    Params.Enum_property:
      properties:
        choices:
          items:
            $ref: ../choice/choice.yaml#/components/schemas/Choice
          type: array
          x-field-uid: 1
      type: object
