components:
  schemas:
    TrafficSettings:
      properties:
        defaulttransportprofile:
          $ref: ../transportprofile/transportprofile.yaml#/components/schemas/TransportProfile
          x-field-uid: 1
        links:
          items:
            $ref: ../apilink/apilink.yaml#/components/schemas/APILink
          type: array
          x-field-uid: 2
      type: object
