components:
  schemas:
    TrafficSettings:
      properties:
        defaulttransportprofile:
          $ref: ../transportprofile/transportprofile.yaml#/components/schemas/TransportProfile
          x-field-uid: 1
      type: object
