components:
  schemas:
    Application:
      properties:
        actiontimeout:
          x-field-uid: 19
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/actiontimeout
        active:
          x-field-uid: 20
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/active
        clienthttpprofile:
          x-field-uid: 21
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/clienthttpprofile
        clienttlsprofile:
          $ref: ../tls/tls.yaml#/components/schemas/tls
          x-field-uid: 1
        connections:
          x-field-uid: 22
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/connections
        connectionsmaxtransactions:
          x-field-uid: 23
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/connectionsmaxtransactions
        datatypes:
          items:
            $ref: ../datatype/datatype.yaml#/components/schemas/DataType
          type: array
          x-field-uid: 2
        description:
          x-field-uid: 24
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/description
        destinationhostname:
          x-field-uid: 25
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/destinationhostname
        dnnid:
          x-field-uid: 26
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/dnnid
        endpointid:
          x-field-uid: 27
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/endpointid
        endpoints:
          x-field-uid: 28
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/endpoints
        externalresourceurl:
          x-field-uid: 29
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/externalresourceurl
        index:
          x-field-uid: 30
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/index
        inherithttpprofile:
          x-field-uid: 31
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/inherithttpprofile
        inherittls:
          default: true
          type: boolean
          x-field-uid: 3
        ippreference:
          x-field-uid: 32
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/ippreference
        isdeprecated:
          x-field-uid: 33
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/isdeprecated
        isstatelessstream:
          type: boolean
          x-field-uid: 4
        iterationcount:
          x-field-uid: 34
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/iterationcount
        maxactivelimit:
          x-field-uid: 35
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/maxactivelimit
        modify_excluded_dut_recursively:
          items:
            $ref: ../updatenetworkmapping/updatenetworkmapping.yaml#/components/schemas/UpdateNetworkMapping
          type: array
          x-field-uid: 15
        modify_tags_recursively:
          items:
            $ref: ../updatenetworkmapping/updatenetworkmapping.yaml#/components/schemas/UpdateNetworkMapping
          type: array
          x-field-uid: 16
        name:
          x-field-uid: 36
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/name
        networkmapping:
          x-field-uid: 37
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/networkmapping
        objectiveweight:
          description: The objective weight of the application.
          format: int64
          type: integer
          x-field-uid: 5
        params:
          x-field-uid: 38
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/params
        protocolid:
          x-field-uid: 39
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/protocolid
        qosflowid:
          x-field-uid: 40
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/qosflowid
        readonlymaxtrans:
          x-field-uid: 41
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/readonlymaxtrans
        serverhttpprofile:
          x-field-uid: 42
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/serverhttpprofile
        servertlsprofile:
          $ref: ../tls/tls.yaml#/components/schemas/tls
          x-field-uid: 6
        statelessstream:
          $ref: ../statelessstream/statelessstream.yaml#/components/schemas/StatelessStream
          x-field-uid: 7
        static:
          default: false
          type: boolean
          x-field-uid: 8
        supportedapps:
          items:
            type: string
          type: array
          x-field-uid: 9
        supportscalibration:
          default: false
          type: boolean
          x-field-uid: 10
        supportsclienthttpprofile:
          x-field-uid: 43
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/supportsclienthttpprofile
        supportshttpprofiles:
          x-field-uid: 44
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/supportshttpprofiles
        supportsserverhttpprofile:
          x-field-uid: 45
          x-include: ../scenario/scenario.yaml#/components/schemas/Scenario/properties/supportsserverhttpprofile
        supportsstrikes:
          default: true
          type: boolean
          x-field-uid: 11
        supportstls:
          default: true
          type: boolean
          x-field-uid: 12
        tracks:
          items:
            $ref: ../track/track.yaml#/components/schemas/Track
          type: array
          x-field-uid: 13
      required:
      - objectiveweight
      type: object
