openapi: 3.1.0

info:
  title: Capture models
  version: ^0.0.0

components:
  schemas:
    Capture:
      description: >-
        Capture model
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        port_names:
          description: >-
            A list of port names to configure capture settings on
          type: array
          items:
            type: string
            x-constraint:
            - '/components/schemas/Port.properties.name'
        filters:
          description: >-
            Under development
          type: string
        