components:
  schemas:
    DTLSSettings:
      properties:
        links:
          items:
            $ref: ../apilink/apilink.yaml#/components/schemas/APILink
          type: array
          x-field-uid: 3
        tlsclientprofile:
          $ref: ../tlsprofile/tlsprofile.yaml#/components/schemas/TLSProfile
          default: method(GetDefaultClientTlsProfileDTLSSettings)
          x-field-uid: 1
        udpprofile:
          $ref: ../udpprofile/udpprofile.yaml#/components/schemas/UdpProfile
          x-field-uid: 2
      type: object
