components:
  schemas:
    DTLSSettings:
      properties:
        tlsclientprofile:
          $ref: ../tls/tls.yaml#/components/schemas/tls
          x-field-uid: 1
        udpprofile:
          $ref: ../udp/udp.yaml#/components/schemas/udp
          x-field-uid: 2
      type: object
