components:
  schemas:
    ConfigValidation:
      properties:
        isvalidated:
          type: boolean
          x-field-uid: 1
        links:
          items:
            $ref: ../apilink/apilink.yaml#/components/schemas/APILink
          type: array
          x-field-uid: 3
        validationmessages:
          items:
            $ref: ../validationmessage/validationmessage.yaml#/components/schemas/ValidationMessage
          type: array
          x-field-uid: 2
      required:
      - isvalidated
      type: object
