components:
  schemas:
    Device.DhcpParams:
      description: >-
        Configuration Parameter request list by emulated DHCPv4 Client.
      type: object
      properties:    
        subnet_mask:
            description: >-
              Request for the subnet mask option specifies the client's subnet mask as per RFC950. 
            type: boolean
            default: true
            x-field-uid: 1
        router:
            description: >-
              Request for the router option that specifies a list of IP addresses for routers on the
              client's subnet.
            type: boolean
            default: true
            x-field-uid: 2
        renewal_time:
          description: >-
            Request for the renewal timer, T1, when the timer expire, the client transitions from the BOUND state to the RENEWING state
          type: boolean
          default: false
          x-field-uid: 3
        rebinding_timer:
          description: >-
            Request for the rebinding timer (T2), when expires, the client transitions to the REBINDING state.
          type: boolean
          default: false
          x-field-uid: 4
        client_port:
          description: >-
            The UDP port on which the client listens for DHCP and BOOTP responses.
            The default value port number is 68.
          type: integer
          format: uint32
          minimum: 1
          maximum: 65535
          default: 68
          x-field-uid: 5
        server_port:
          description: >-
            The UDP port to which the client addresses its server requests.
            The default value port number is 67.
          type: integer
          format: uint32
          minimum: 1
          maximum: 65535
          default: 67
          x-field-uid: 6
        discovery_timeout:
          description: >-
            The UDP port to which the client addresses its server requests.
            The default value port number is 67.
          type: integer
          format: uint32
          minimum: 1
          maximum: 65535
          default: 67
          x-field-uid: 7
        discovery_timeout_factor:
          description: >-
            The UDP port to which the client addresses its server requests.
            The default value port number is 67.
          type: integer
          format: uint32
          minimum: 1
          maximum: 100
          default: 2
          x-field-uid: 8
        max_discover_timeout:
          description: >-
            The maximum discover time period in seconds between DHCP Discover reattempt messages. 
            This value is being obtained by factoring in the Discover Timeout Factor parameter.
          type: integer
          format: uint32
          minimum: 1
          maximum: 10000
          default: 64
          x-field-uid: 9
        discover_reattempts:
          description: >-
            Number of times that the client will retransmit a request for which it has not been received a response.
          type: integer
          format: uint32
          minimum: 0
          maximum: 100
          default: 3
          x-field-uid: 10
        selecting_server:
          description: >-
            The client receives one or more DHCPOFFER messages from one or more servers.  The client may choose to wait for multiple responses.
            The client chooses one server from which to request configuration
            parameters, based on the configuration parameters offered in the DHCPOFFER messages.
            use_first_server: if selected, the subnet accepts the IP addresses offered by the first server to respond with an offer of IP addresses.
            use_server_address: The address of the DHCP server from which the subnet will accept IP addresses.
            server address to 0.0.0.0, implementation will use the services of the first DHCP server that responds to the DHCP Lease Request message.
          type: string
          format: ipv4
          default: 0.0.0.0
          x-field-uid: 11
        first_server:
          type: string
          format: ipv4
          default: 0.0.0.0
          x-field-uid: 12
        server_address:
          type: string
          format: ipv4
          default: 0.0.0.0
          x-field-uid: 13
        broadcast:
          description: >-
            If the broadcast bit is set, then the server and relay agent broadcast DHCPOFFER and DHCPACK messages.
          type: boolean
          default: false
          x-field-uid: 14
        gateway_ip: 
          description: >-
            A manually configured IPv4 gateway address. 
            The default value 0.0.0.0, meaning that no manual gateway IP address is specified.
            If the DHCPv4 Client receives from a server a response packet with a Router Address TLV 
            specifying another gateway address than the manually configured gateway IP, 
            then this TLV is ignored. 
            Whenever a manual non default gateway IP is configured, the client will use it as gateway address 
            for traffic outside of its network; 
            otherwise client uses the gateway IP address learned from the server.
          type: string
          format: ipv4
          default: 0.0.0.0
          x-field-uid: 15
        gateway_mac:
          description: >-
            A manually configured gateway MAC address. 
            In case of non default, ARP messages are sent to resolve the gateway MAC address.
          type: string
          format: mac
          default: "0:0:0:0:0:0"
          x-field-uid: 16