components:
  schemas:
    AdvancedMetrics.Config:
      description: |-
        The container for advanced metrics configuration.
      type: object
      properties:
        timestamps:
          $ref: '#/components/schemas/AdvancedMetrics.Config.Timestamp'
        convergence:
          $ref: '#/components/schemas/AdvancedMetrics.Config.Convergence'
        latency:
          $ref: '#/components/schemas/AdvancedMetrics.Config.Latency'

    AdvancedMetrics.Config.Timestamp:
      description: |-
        The optional container for timestamp metric configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable timestamp metrics. 
          type: boolean
          default: false
        synchronization:
          description: |-
            Timestamps will be synchronized to either the system clock or offset
            from the start of the flow.
          type: string
          enum: [start_of_flow, system_clock]
          default: start_of_flow

    AdvancedMetrics.Config.Convergence:
      description: |-
        The optional container for convergence metric configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable convergence metrics. 
            See the #/components/schemas/Event.Occurence/properties/event
            property for a list of all possible types of events.
          type: boolean
          default: false
        rx_rate_threshold:
          description: |-
            An event will be generated when the rx rate passes
            above or below this value.
          type: number
          maximum: 100
          format: float
          default: 95

    AdvancedMetrics.Config.Latency:
      description: |-
        The optional container for latency metric configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable latency metrics
          type: boolean
          default: false
        mode:
          description: |-
            Select the type of latency measurement. The different types of 
            latency measurements are:
            

            store_forward:
            The time interval starting when the last bit of the frame leaves the
            sending port and ending when the first bit of the frame is seen on
            the receiving port (LIFO).  This is based on the RFC 1242 standard.


            cut_through:
            The time interval starting when the first bit of the frame leaves
            the sending port and ending when the first bit of the frame is seen
            on the receiving port (FIFO).  This is based on the RFC 1242 
            standard.
          type: string
          enum: 
          - store_forward
          - cut_through
          default: store_forward


