components:
  schemas:
    Advanced.Config:
      description: |-
        An optional container for the configuration of advanced features.
      type: object
      properties:
        latency:
          $ref: '#/components/schemas/Advanced.Config.Latency'
        event:
          $ref: '#/components/schemas/Advanced.Config.Event'
        convergence:
          $ref: '#/components/schemas/Advanced.Config.Convergence'

    Advanced.Config.Latency:
      description: |-
        The optional container for latency metric configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable latency metrics using timestamps.


            Enabling this option requires enabling flow metrics using the 
            /components/schemas/Flow/properties/metrics option.


            Enabling this option may affect the resultant packet payload due to 
            additional instrumentation data.
          type: boolean
          default: false
        mode:
          description: |-
            Select the type of latency measurement. The different types of 
            latency measurements are:
            

            store_forward:
            The time interval starting when the last bit of the frame leaves the
            sending port and ending when the first bit of the frame is seen on
            the receiving port (LIFO).  This is based on the RFC 1242 standard.


            cut_through:
            The time interval starting when the first bit of the frame leaves
            the sending port and ending when the first bit of the frame is seen
            on the receiving port (FIFO).  This is based on the RFC 1242 
            standard.
          type: string
          enum: 
          - store_forward
          - cut_through
          default: store_forward

    Advanced.Config.Convergence:
      description: |-
        The optional container for convergence analytics configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable convergence analytics. 


            Enabling this option requires enabling the rx_rate_threshold event 
            using the /components/schemas/Advanced.Config.Event/properties/rx_rate_threshold option.


            Enabling this option may affect the resultant packet payload due to 
            additional instrumentation data.
          type: boolean
          default: false

    Advanced.Config.Event:
      description: |-
        The optional container for event configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable all events. 
            Enabling this option may affect the resultant packet payload due to 
            additional instrumentation data.
          type: boolean
          default: false
        link_up_down:
          $ref: '#/components/schemas/Advanced.Config.LinkUpDown'
        rx_rate_threshold:
          $ref: '#/components/schemas/Advanced.Config.RxRateThreshold'
        route_advertise_withdraw:
          $ref: '#/components/schemas/Advanced.Config.RouteAdvertiseWithdraw'

    Advanced.Config.RxRateThreshold:
      description: |-
        The optional container for rx rate threshold event configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable the rx_rate_threshold event. 
            Enabling this option may affect the resultant packet payload due to 
            additional instrumentation data.
          type: boolean
          default: false
        threshold:
          description: |-
            True to enable notifications when the rx rate of a flow passes above 
            or below the threshold value. 
          type: number
          format: float
          maximum: 100
          minimum: 0
          default: 95

    Advanced.Config.LinkUpDown:
      description: |-
        The optional container for link up/down event configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable notifications when a link up/down event occurs. 
          type: boolean
          default: false

    Advanced.Config.RouteAdvertiseWithdraw:
      description: |-
        The optional container for route advertise/withdraw event configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable notifications when a route advertise/withdraw 
            event occurs. 
          type: boolean
          default: false
