components:
  schemas:
    Advanced.Config:
      description: |-
        The container for the configuration of advanced features.
      type: object
      properties:
        flows:
          $ref: '#/components/schemas/Advanced.Config.Flows'
        timestamps:
          $ref: '#/components/schemas/Advanced.Config.Timestamp'
        latency:
          $ref: '#/components/schemas/Advanced.Config.Latency'
        event:
          $ref: '#/components/schemas/Advanced.Config.Event'
        convergence:
          $ref: '#/components/schemas/Advanced.Config.Convergence'

    Advanced.Config.Flows:
      description: |-
        The optional container for flows metric configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable metrics for configured flows.
            Enabling this option could possibly change the packet payload as 
            implementations may add instrumentation values to identify which 
            flow a packet is associated with.
          type: boolean
          default: false

    Advanced.Config.Timestamp:
      description: |-
        The optional container for flow timestamp metric configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable timestamp metrics. 
            This adds first and last timestamp metrics to individual flows.
          type: boolean
          default: false
        synchronization:
          description: |-
            Timestamps will be synchronized to either the system clock or offset
            from the start of the flow.
          type: string
          enum: [start_of_flow, system_clock]
          default: start_of_flow

    Advanced.Config.Latency:
      description: |-
        The optional container for latency metric configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable latency metrics
          type: boolean
          default: false
        mode:
          description: |-
            Select the type of latency measurement. The different types of 
            latency measurements are:
            

            store_forward:
            The time interval starting when the last bit of the frame leaves the
            sending port and ending when the first bit of the frame is seen on
            the receiving port (LIFO).  This is based on the RFC 1242 standard.


            cut_through:
            The time interval starting when the first bit of the frame leaves
            the sending port and ending when the first bit of the frame is seen
            on the receiving port (FIFO).  This is based on the RFC 1242 
            standard.
          type: string
          enum: 
          - store_forward
          - cut_through
          default: store_forward

    Advanced.Config.Convergence:
      description: |-
        The optional container for convergence analytics configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable convergence analytics. 
          type: boolean
          default: false

    Advanced.Config.Event:
      description: |-
        The optional container for event configuration.
      type: object
      properties:
        enable:
          description: |-
            True to enable events. 
          type: boolean
          default: false
        rx_rate_threshold:
          description: |-
            An event will be generated when the rx rate passes
            above or below this value.
          type: number
          maximum: 100
          format: float
          default: 95

