components:
  schemas:
    P2Config:
      properties:
        encalgorithm:
          $ref: ../encp2algorithm/encp2algorithm.yaml#/components/schemas/EncP2Algorithm
          x-field-uid: 1
        hashalgorithm:
          $ref: ../hashp2algorithm/hashp2algorithm.yaml#/components/schemas/HashP2Algorithm
          x-field-uid: 2
        lifetime:
          format: int32
          type: integer
          x-field-uid: 3
        natenabled:
          type: boolean
          x-field-uid: 4
        pfsenabled:
          type: boolean
          x-field-uid: 5
        pfsgroup:
          $ref: ../pfsp2group/pfsp2group.yaml#/components/schemas/PfsP2Group
          x-field-uid: 6
      required:
      - lifetime
      - encalgorithm
      - hashalgorithm
      - pfsenabled
      - pfsgroup
      - natenabled
      type: object
