openapi: 3.1.0

info:
  title: Duration models
  version: ^0.0.0

components:
  schemas:
    Flow.Duration:
      description: >-
        A container for different transmit durations. 
      type: object
      properties:
        choice:
          type: string
          enum: [packets, seconds, burst, continuous]
        packets:
          $ref: '#/components/schemas/Flow.FixedPackets'
        seconds:
          $ref: '#/components/schemas/Flow.FixedSeconds'
        burst:
          $ref: '#/components/schemas/Flow.Burst'
        continuous:
          $ref: '#/components/schemas/Flow.Continuous'

    Flow.Continuous:
      description: >-
        Transmit will be continuous and will not stop automatically. 
      type: object
      properties:
        gap:
          description: >-
            The minimum gap between packets expressed as bytes.
          type: integer
          default: 12
        delay:
          description: >-
            The delay before starting transmission of packets.
          type: integer
          default: 0
        delay_unit:
          description: >-
            The delay expressed as a number of this value.
          type: string
          enum: [bytes, nanoseconds]
          default: bytes

    Flow.FixedPackets:
      description: >-
        Transmit a fixed number of packets after which the flow will stop.
      type: object      
      properties:
        packets:
          description: >-
            Stop transmit of the flow after this number of packets.
          type: integer
          default: 1
        gap:
          description: >-
            The minimum gap between packets expressed as bytes.
          type: integer
          default: 12
        delay:
          description: >-
            The delay before starting transmission of packets.
          type: integer
          default: 0
        delay_unit:
          description: >-
            The delay expressed as a number of this value.
          type: string
          enum: [bytes, nanoseconds]
          default: bytes

    Flow.FixedSeconds:
      description: >-
        Transmit for a fixed number of seconds after which the flow will stop.
      type: object      
      properties:
        seconds:
          description: >-
            Stop transmit of the flow after this number of seconds.
          type: number
          default: 1
        gap:
          description: >-
            The minimum gap between packets expressed as bytes.
          type: integer
          default: 12
        delay:
          description: >-
            The delay before starting transmission of packets.
          type: integer
          default: 0
        delay_unit:
          description: >-
            The delay expressed as a number of this value.
          type: string
          enum: [bytes, nanoseconds]
          default: bytes

    Flow.Burst:
      description: >-
        A continuous burst of packets that will not automatically stop.
      type: object      
      properties:
        packets:
          description: >-
            The number of packets transmitted per burst.
          type: integer
          minimum: 1
        gap:
          description: >-
            The minimum gap between packets expressed as bytes.
          type: integer
          default: 12
        inter_burst_gap:
          description: >-
            The gap between the transmission of each burst.
            A value of 0 means there is no gap between bursts.
          type: integer
          default: 0
        inter_burst_gap_unit:
          description: >-
            The inter burst gap expressed as a number of this value.
          type: string
          enum: [bytes, nanoseconds]
          default: bytes


