openapi: 3.1.0

info:
  title: Duration models
  version: ^0.0.0

components:
  schemas:
    Flow.Duration:
      description: >-
        A container for different transmit durations. 
      type: object
      required: [choice]
      properties:
        choice:
          description: |-
            A choice used to determine the type of duration.
          type: string
          enum: [fixed_packets, fixed_seconds, burst, continuous]
        fixed_packets:
          $ref: '#/components/schemas/Flow.FixedPackets'
        fixed_seconds:
          $ref: '#/components/schemas/Flow.FixedSeconds'
        burst:
          $ref: '#/components/schemas/Flow.Burst'
        continuous:
          $ref: '#/components/schemas/Flow.Continuous'

    Flow.Continuous:
      description: >-
        Transmit will be continuous and will not stop automatically. 
      type: object
      properties:
        gap:
          description: >-
            The minimum gap between packets expressed as bytes.
          type: integer
          default: 12
        delay:
          $ref: '#/components/schemas/Flow.Delay'
    
    Flow.Delay:
      description: >-
        The optional container to specify the delay before starting 
        transmission of packets.
      type: object
      required: [choice]
      properties:
        choice:
          type: string
          enum: [bytes, nanoseconds, microseconds]
        bytes:
          description: >-
            The delay before starting transmission of packets.
            A value of 0 indicates no gap between bursts.
          type: number
          format: float
          default: 0
        nanoseconds:
          description: >-
            The delay before starting transmission of packets.
            A value of 0 indicates no gap between bursts.
          type: number
          format: float
          default: 0
        microseconds:
          description: >-
            The delay before starting transmission of packets.
            A value of 0 indicates no gap between bursts.
          type: number
          format: float
          default: 0

    Flow.FixedPackets:
      description: >-
        Transmit a fixed number of packets after which the flow will stop.
      type: object      
      properties:
        packets:
          description: >-
            Stop transmit of the flow after this number of packets.
          type: integer
          default: 1
        gap:
          description: >-
            The minimum gap between packets expressed as bytes.
          type: integer
          default: 12
        delay:
          $ref: '#/components/schemas/Flow.Delay'

    Flow.FixedSeconds:
      description: >-
        Transmit for a fixed number of seconds after which the flow will stop.
      type: object      
      properties:
        seconds:
          description: >-
            Stop transmit of the flow after this number of seconds.
          type: number
          default: 1
        gap:
          description: >-
            The minimum gap between packets expressed as bytes.
          type: integer
          default: 12
        delay:
          $ref: '#/components/schemas/Flow.Delay'

    Flow.Burst:
      description: >-
        Transmits continuous or fixed burst of packets. 
        For continuous burst of packets, it will not automatically stop.
        For fixed burst of packets, it will stop after transmitting fixed number of bursts.      
      type: object      
      properties:
        bursts:
          description: >-
            The number of packet bursts transmitted per flow.
            A value of 0 implies continuous burst of packets.
          type: integer
          default: 0
        packets:
          description: >-
            The number of packets transmitted per burst.
          type: integer
          minimum: 1
        gap:
          description: >-
            The minimum gap between packets expressed as bytes.
          type: integer
          default: 12
        inter_burst_gap:
          $ref: '#/components/schemas/Flow.Duration.InterBurstGap'
    
    Flow.Duration.InterBurstGap:
      type: object
      description: |-
        The optional container for specifying a gap between bursts.
      required: [choice]
      properties:
        choice:
          description: |-
            The type of inter burst gap units.
          type: string
          enum: [bytes, nanoseconds, microseconds]
          default: bytes
        bytes:
          description: |-
            The amount of time between bursts expressed in bytes.
            A value of 0 indicates no gap between bursts.
          type: number
          format: double
          default: 12
        nanoseconds:
          description: |-
            The amount of time between bursts expressed in nanoseconds.
            A value of 0 indicates no gap between bursts.
          type: number
          format: double
          default: 96
        microseconds:
          description: |-
            The amount of time between bursts expressed in microseconds.
            A value of 0 indicates no gap between bursts.
          type: number
          format: double
          default: .096


