openapi: 3.1.0

info:
  title: Flow model
  version: ^0.0.0

components:
  schemas:
    Flow:
      x-include: 
      - '../common/common.yaml#/components/schemas/Named.Object'
      description: >- 
        A high level data plane traffic flow.
        Acts as a container for endpoints, packet headers, packet size, 
        transmit rate and transmit duration.
      type: object
      required: [tx_rx]
      properties:
        tx_rx:
          description: >-
            The transmit and receive endpoints.
          $ref: './endpoint.yaml#/components/schemas/Flow.TxRx'
        packet:
          description: >-
            The header is a list of traffic protocol headers.
            The order of traffic protocol headers assigned to the list is the
            order they will appear on the wire.
          type: array
          items:
            $ref: './packet-headers/header.yaml#/components/schemas/Flow.Header'
        size:
          description: >-
            The size of the packets.
          $ref: './size.yaml#/components/schemas/Flow.Size'
        rate:
          description: >-
            The transmit rate of the packets.
          $ref: './rate.yaml#/components/schemas/Flow.Rate'
        duration:
          description: >-
            The transmit duration of the packets.
          $ref: './duration.yaml#/components/schemas/Flow.Duration'
     
      
