openapi: 3.0.3
info:
  title: Port pattern model
  version: ^0.0.0
components:
  schemas:
    Flow.PortPattern:
      description: >-
        A pattern that is applied to a test port.
        The name of the pattern will be reflected in the port results.
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        offset:
          type: integer
          format: uint32
          description: >-
            The offset from the beginning of the packet
          x-field-uid: 2
        pattern:
          type: string
          description: >-
            The value of the pattern
          x-field-uid: 3
        mask:
          type: string
          description: >-
            The mask value to be applied against the pattern
          x-field-uid: 4
