openapi: 3.0.2

info:
  title: Rate data model
  version: ^0.0.0
  
paths: {}

components:
  schemas:
    Flow.Rate:
      type: object
      description: >-
        The rate of packet transmission
      required: [choice]
      properties:
        choice:
          type: string
          enum: [pps, bps, kbps, mbps, gbps, percentage]
          default: pps
        pps:
          description: >-
            Packets per second.
          type: integer
          default: 1000
        bps:
          description: >-
            Bits per second.
          type: integer
        kbps:
          description: >-
            Kilobits per second.
          type: number
        mbps:
          description: >-
            Megabits per second.
          type: number
        gbps:
          description: >-
            Gigabits per second.
          type: number
        percentage:
          description: >-
            The percentage of a port location's available bandwidth.
          type: number

