components:
  schemas:
    AppsecConfig:
      properties:
        config:
          $ref: ../config/config.yaml#/components/schemas/Config
          x-field-uid: 1
        configtypename:
          description: Used for API clients to decide what type of config they have
            loaded
          type: string
          x-field-uid: 4
        datamodelversion:
          description: The version of the data model used for this configuration
          type: string
          x-field-uid: 5
        name:
          description: The name of the configuration
          type: string
          x-field-uid: 6
        sessionid:
          description: The unique identifier of the session this configuration belongs
            to
          type: string
          x-field-uid: 2
        templateid:
          description: The unique identifier of the CyPerf configuration template
            from which this configuration was created
          type: string
          x-field-uid: 3
      required:
      - configtypename
      type: object
