components:
  schemas:
    HealthCheckConfig:
      description: The HealthCheck configuration for DUT
      properties:
        enabled:
          default: true
          description: 'A flag indicating if the servers should listen for HealthCheck
            requests (default: true).'
          type: boolean
          x-field-uid: 1
        links:
          items:
            $ref: ../apilink/apilink.yaml#/components/schemas/APILink
          type: array
          x-field-uid: 4
        params:
          description: A list of additional parameters for the HealthCheck.
          items:
            $ref: ../params/params.yaml#/components/schemas/Params
          type: array
          x-field-uid: 2
        port:
          default: 80
          description: 'The port that the DUT will send HealthCheck requests to the
            simulated servers. (default: 80)'
          format: int32
          type: integer
          x-field-uid: 3
      type: object
