openapi: 3.1.0

info:
  title: Layer1 models
  version: ^0.0.0

components:
  schemas:
    Layer1:
      x-include: 
      - '../common/common.yaml#/components/schemas/Named.Object'
      description: >-
        A container for layer1 settings.
      type: object
      required: [port_names]
      properties:
        port_names:
          description: >- 
            A list of unique names of port objects that will share the
            choice settings. 
          type: array
          items:
            type: string
            x-constraint:
            - '/components/schemas/Port/properties/name'
        speed:
          description: >-
            Set the speed if supported.
          type: string
          enum:
            - speed_10_fd_mbps
            - speed_10_hd_mbps
            - speed_100_fd_mbps
            - speed_100_hd_mbps
            - speed_1_gbps
            - speed_10_gbps
            - speed_25_gbps
            - speed_40_gbps
            - speed_100_gbps
            - speed_200_gbps
            - speed_400_gbps
          default: speed_10_gbps
        media:
          description: >-
            Set the type of media interface if supported.
          type: string
          enum:
            - copper
            - fiber
            - sgmii
        promiscuous:
          description: >-
            Enable promiscuous mode if supported.
          type: boolean
          default: false
        mtu:
          description: >-
            Set the maximum transmission unit size if supported.
          type: integer
          default: 1500
        ieee_media_defaults:
          description: >-
            Set to true to override the auto_negotiate, link_training
            and rs_fec settings for gigabit ethernet interfaces.
          type: boolean
          default: true
        auto_negotiate:
          description: >-
            Enable/disable auto negotiation.
          type: boolean
          default: true
        auto_negotiation:
          $ref: '#/components/schemas/Layer1.AutoNegotiation'
        flow_control:
          $ref: '#/components/schemas/Layer1.FlowControl'

    Layer1.AutoNegotiation:
      description: >-
        Container for auto negotiation settings
      type: object
      properties:
        advertise_1000_mbps:
          description: >-
            If auto_negotiate is true and the interface supports this option
            then this speed will be advertised.
          type: boolean
          default: true
        advertise_100_fd_mbps:
          description: >-
            If auto_negotiate is true and the interface supports this option
            then this speed will be advertised.
          type: boolean
          default: true
        advertise_100_hd_mbps:
          description: >-
            If auto_negotiate is true and the interface supports this option
            then this speed will be advertised.
          type: boolean
          default: true
        advertise_10_fd_mbps:
          description: >-
            If auto_negotiate is true and the interface supports this option
            then this speed will be advertised.
          type: boolean
          default: true
        advertise_10_hd_mbps:
          description: >-
            If auto_negotiate is true and the interface supports this option
            then this speed will be advertised.
          type: boolean
          default: true
        link_training:
          description: >-
            Enable/disable gigabit ethernet link training.
          type: boolean
          default: false
        rs_fec:
          description: >-
            Enable/disable gigabit ethernet reed solomon forward error correction (RS FEC).
          type: boolean
          default: false

    Layer1.FlowControl:
      description: >-
        A container for layer1 receive flow control settings.
        To enable flow control settings on ports this object must be a valid
        object not a null value.
      type: object
      properties:
        directed_address:
          description: >-
            The 48bit mac address that the layer1 port names will listen on
            for a directed pause.  
          type: string
          default: 0180C2000001
        choice:
          description: >- 
            The type of priority flow control.
          type: string
          enum: [ieee_802_1qbb, ieee_802_3x]
        ieee_802_1qbb:
          $ref: '#/components/schemas/Layer1.Ieee8021qbb'
        ieee_802_3x:
          $ref: '#/components/schemas/Layer1.Ieee8023x'

    Layer1.Ieee8023x:
      description: >-
        A container for ieee 802.3x rx pause settings
      type: object

    Layer1.Ieee8021qbb:
      description: >-
        These settings enhance the existing 802.3x pause priority capabilities 
        to enable flow control based on 802.1p priorities (classes of service). 
      type: object
      properties:
        pfc_delay:
          description: >-
            The upper limit on the transmit time of a queue after receiving a 
            message to pause a specified priority.
            A value of 0 or null indicates that pfc delay will not be enabled. 
          type: integer
        pfc_class_0:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_1:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_2:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_3:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_4:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_5:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_6:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_7:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer

