openapi: 3.1.0

info:
  title: Layer1 models
  version: ^0.0.0

components:
  schemas:
    Layer1:
      description: >-
        A container for layer1 settings.
      type: object
      required: [name, choice]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        port_names:
          description: >- 
            A list of unique names of a port objects that will share the 
            choice settings. 
          type: array
          items:
            type: string
            x-constraint:
            - '/components/schemas/Port/properties/name'
        choice:
          description: >-
            The type of layer1 characteristics.
          type: string
          enum: [one_hundred_gbe, ethernet]
        one_hundred_gbe:
          $ref: '#/components/schemas/Layer1.OneHundredGbe'
        ethernet:
          $ref: '#/components/schemas/Layer1.Ethernet'

    Layer1.OneHundredGbe:
      description: >-
        Container for 100 gigabit ethernet settings
      type: object
      properties:
        ieee_media_defaults:
          description: >-
            Enable/disable ieee media default settings.
            True will override the speed, auto_negotiate, link_training, rs_fec settings.
          type: boolean
          default: true
        auto_negotiate:
          description: >-
            Enable/disable auto negotiation.
          type: boolean
          default: false
        link_training:
          description: >-
            Enable/disable link training.
          type: boolean
          default: false
        rs_fec:
          description: >-
            Enable/disable reed solomon forward error correction (RS FEC).
          type: boolean
          default: false
        speed:
          description: >-
            This is the speed that will be used if auto_negotiate is false.
          type: string
          enum: [100_gbps, 50_gbps, 40_gbps, 25_gpbs, 10_gbps]
          default: 100_gbps
        flow_control:
          $ref: '#/components/schemas/Layer1.FlowControl'
    
    Layer1.EthernetVirtual:
      description: >-
        Container for virtual ethernet settings
      type: object
      properties:
        speed:
          description: >-
            This is the speed that will be set on the virtual ethernet interface.
          type: string
          enum: [100_mbps, 1_gbps, 10_gbps, 25_gbps, 50_gbps, 100_gbps]
          default: 10_gbps

    Layer1.Ethernet:
      description: >-
        Container for 10/100/1000 ethernet settings
      type: object
      properties:
        media:
          type: string
          enum: [copper, fiber]
          default: copper
        speed:
          description: >-
            This is the speed that will be used if auto_negotiate is false.
          type: string
          enum: [1000_mbps, 100_fd_mbps, 100_hd_mbps, 10_fd_mbps, 10_hd_mbps]
          default: 1000_mbps
        auto_negotiate:
          description: >-
            Enable/disable auto negotiation.
          type: boolean
          default: true
        advertise_1000_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        advertise_100_fd_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        advertise_100_hd_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        advertise_10_fd_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        advertise_10_hd_mbps:
          description: >-
            If auto_negotiate is true then this speed will be advertised.
          type: boolean
          default: true
        flow_control:
          $ref: '#/components/schemas/Layer1.FlowControl'

    Layer1.FlowControl:
      description: >-
        A container for layer1 receive flow control settings.
        To enable flow control settings on ports this object must be a valid
        object not a null value.
      type: object
      properties:
        directed_address:
          description: >-
            The 48bit mac address that the layer1 port names will listen on
            for a directed pause.  
          type: string
          default: 0180C2000001
        choice:
          description: >- 
            The type of priority flow control.
          type: string
          enum: [ieee_802_1qbb, ieee_802_3x]
        ieee_802_1qbb:
          $ref: '#/components/schemas/Layer1.Ieee8021qbb'
        ieee_802_3x:
          $ref: '#/components/schemas/Layer1.Ieee8023x'

    Layer1.Ieee8023x:
      description: >-
        A container for ieee 802.3x rx pause settings
      type: object

    Layer1.Ieee8021qbb:
      description: >-
        These settings enhance the existing 802.3x pause priority capabilities 
        to enable flow control based on 802.1p priorities (classes of service). 
      type: object
      properties:
        pfc_delay:
          description: >-
            The upper limit on the transmit time of a queue after receiving a 
            message to pause a specified priority.
            A value of 0 or null indicates that pfc delay will not be enabled. 
          type: integer
        pfc_class_0:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_1:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_2:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_3:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_4:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_5:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_6:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer
        pfc_class_7:
          description: >-
            The valid values are null, 0 - 7.
            A null value indicates there is no setting for this pfc class.
          type: integer

