components:
  schemas:
    AdvancedSettings:
      properties:
        agentoptimizationmode:
          $ref: ../agentoptimizationmode/agentoptimizationmode.yaml#/components/schemas/AgentOptimizationMode
          x-field-uid: 1
        agentstreamingpurposecpupercent:
          default: 25
          description: 'The CPU percentage reserved for streaming purpose use (default:
            0).'
          format: int32
          type: integer
          x-field-uid: 2
        automaticcpupercent:
          default: true
          description: Deprecated. Use the calibration operation to find the best
            value for AgentStreamingPurposeCPUPercent for the current assigned agents.
          type: boolean
          x-field-uid: 3
        connectiongracefulstoptimeout:
          default: 120
          description: 'The time the test will wait all connections to be graceful
            stopped (default: 15 seconds).'
          format: int64
          type: integer
          x-field-uid: 4
        warmupperiod:
          description: 'The time that servers may need to warm up, when clients should
            wait (default: 0 seconds).'
          format: int64
          type: integer
          x-field-uid: 5
      required:
      - warmupperiod
      type: object
