components:
  schemas:
    RoCEv2.FlowSettings:
      description: >-
          This section has two views, Local End and Remote End.
           Both views have same configurations. However, the remote and local peer IP addresses are interchanged.
            This configuration allows you to configure RDMA flow over the same QP number from same source and destination.
             Default value for commands at Remote peer is set to None.
              So that by default, this remote peer does not initiate any traffic flow.
      type: object
      properties:
        local_end:
          $ref: './flowsettings.yaml#/components/schemas/RoCEv2.FlowSettings.LocalEnd'
          x-field-uid: 1
        remote_end:
          $ref: './flowsettings.yaml#/components/schemas/RoCEv2.FlowSettings.RemoteEnd'
          x-field-uid: 2

    RoCEv2.FlowSettings.LocalEnd:
      description: >-
        Local End Flow Settings
      type: object
      properties:
        custom_qp:
          description: |-
            Turn on to define QP number.
          type: boolean
          default: false
          x-field-uid: 1
        custom_qp_number:
          description: >-
            Configure the QP range.
          type: integer
          format: uint32
          default: 1
          minimum: 2
          maximum: 33554431
          x-field-uid: 2
        dscp:
          description: >-
            DSCP value for this flow
          type: integer
          format: uint32
          default: 24
          minimum: 0
          maximum: 63
          x-field-uid: 3
        ecn:
          description: >-
            This field allows to configure bits of the Traffic Class field in the IPv4 or IPv6 header to encode four different code points.
          type: integer
          format: uint32
          default: 1
          minimum: 0
          maximum: 3
          x-field-uid: 4
        udp_source_port:
          description: >-
            UDP source port number for this flow.
          type: integer
          format: uint32
          default: 49152
          minimum: 0
          maximum: 65535
          x-field-uid: 5
        execute_commands:
          description: >-
            UDP source port number for this flow.
          type: string
          x-enum:
            none:
              x-field-uid: 1
            RDMAWrite:
              x-field-uid: 2
          x-field-uid: 6
        immediate_data:
          description: >-
            Immediate Data field required for SEND/WRITE with immediate verb.
          type: string
          format: hex
          default: "00 00 00 00"
          x-field-uid: 7
        message_size:
          description: >-
            The Maximum message size that is allowed to transfer depends on the MTU size and the number of VLANs configured on the interfaces.
            For any MTU, the maximum number of segmented RDMA WRITE packets for a single WRITE MESSAGE is 65535.
            That is, a single RDMA WRITE message can be broken into 1 WRITE FIRST, 1 WRITE LAST and (65535-2) WRITE MIDDLE messages.
            The maximum message size that is allowed to be transferred for a given MTU is constrained by the above conditions.
            For example, for an MTU size of 1500 bytes,
            the common header of the RDMA WRITE MIDDLE/LAST will comprise of
            Ethernet Header + IP Header + UDP Header + BTH Header + iCRC size + Ethernet Trailer size. This works out to be 14+20+8+12+4+4 = 62 bytes.
            For RDMA WRITE FIRST, we need to add the RETH header size of 16 bytes to the above, which adds up to 78 bytes.
            Then the maximum message size for 1500 MTU without VLAN becomes:
            1500 - WRITE FIRST common header + 65534 * (1500 - WRITE LAST/MIDDLE header size) = 1500 - 78 + 65534 * (1500 - 62) = 94239314 bytes or 89 MB.
          type: integer
          format: uint32
          default: 1
          minimum: 0
          maximum: 65535
          x-field-uid: 8
        message_size_unit:
          description: >-
            Unit of the transfer message size. Available options are Bytes, KB, MB.
          type: string
          x-enum:
            Byte:
              x-field-uid: 1
            KB:
              x-field-uid: 2
            MB:
              x-field-uid: 3
          x-field-uid: 9
        initial_psn:
          description: >-
            Initial PSN
          type: integer
          format: uint32
          default: 24
          minimum: 0
          maximum: 33554431
          x-field-uid: 10
    RoCEv2.FlowSettings.RemoteEnd:
      description: >-
        Remote End Flow Settings
      type: object
      properties:
        custom_qp:
          description: |-
            Turn on to define QP number.
          type: boolean
          default: false
          x-field-uid: 1
        custom_qp_number:
          description: >-
            Configure the QP range.
          type: integer
          format: uint32
          default: 1
          minimum: 2
          maximum: 33554431
          x-field-uid: 2
        dscp:
          description: >-
            DSCP value for this flow
          type: integer
          format: uint32
          default: 24
          minimum: 0
          maximum: 63
          x-field-uid: 3
        ecn:
          description: >-
            This field allows to configure bits of the Traffic Class field in the IPv4 or IPv6 header to encode four different code points.
          type: integer
          format: uint32
          default: 1
          minimum: 0
          maximum: 3
          x-field-uid: 4
        udp_source_port:
          description: >-
            UDP source port number for this flow.
          type: integer
          format: uint32
          default: 49152
          minimum: 0
          maximum: 65535
          x-field-uid: 5
        execute_commands:
          description: >-
            UDP source port number for this flow.
          type: string
          x-enum:
            none:
              x-field-uid: 1
            RDMAWrite:
              x-field-uid: 2
          x-field-uid: 6
        immediate_data:
          description: >-
            Immediate Data field required for SEND/WRITE with immediate verb.
          type: string
          format: hex
          default: "00 00 00 00"
          x-field-uid: 7
        message_size:
          description: >-
            The Maximum message size that is allowed to transfer depends on the MTU size and the number of VLANs configured on the interfaces.
            For any MTU, the maximum number of segmented RDMA WRITE packets for a single WRITE MESSAGE is 65535.
            That is, a single RDMA WRITE message can be broken into 1 WRITE FIRST, 1 WRITE LAST and (65535-2) WRITE MIDDLE messages.
            The maximum message size that is allowed to be transferred for a given MTU is constrained by the above conditions.
            For example, for an MTU size of 1500 bytes,
            the common header of the RDMA WRITE MIDDLE/LAST will comprise of
            Ethernet Header + IP Header + UDP Header + BTH Header + iCRC size + Ethernet Trailer size. This works out to be 14+20+8+12+4+4 = 62 bytes.
            For RDMA WRITE FIRST, we need to add the RETH header size of 16 bytes to the above, which adds up to 78 bytes.
            Then the maximum message size for 1500 MTU without VLAN becomes:
            1500 - WRITE FIRST common header + 65534 * (1500 - WRITE LAST/MIDDLE header size) = 1500 - 78 + 65534 * (1500 - 62) = 94239314 bytes or 89 MB.
          type: integer
          format: uint32
          default: 1
          minimum: 0
          maximum: 65535
          x-field-uid: 8
        message_size_unit:
          description: >-
            Unit of the transfer message size. Available options are Bytes, KB, MB.
          type: string
          x-enum:
            Byte:
              x-field-uid: 1
            KB:
              x-field-uid: 2
            MB:
              x-field-uid: 3
          x-field-uid: 9
        remote_qp_number:
          description: >-
            Remote QP Number.
          type: integer
          format: uint32
          default: 0
          minimum: 0
          maximum: 33554431
          x-field-uid: 10
        virtual_address:
          description: >-
            Remote virtual address.
          type: string
          format: hex
          default: "00 00 00 00 00 00 00 00"
          x-field-uid: 11
        remote_key:
          description: >-
            Remote Key.
          type: string
          format: hex
          default: "00 00 00 00"
          x-field-uid: 12
        initial_psn:
          description: >-
            Initial PSN.
          type: integer
          format: uint32
          default: 0
          minimum: 0
          maximum: 33554431
          x-field-uid: 13
    
