components:
  schemas:
    RoCEv2.FlowSettings:
      description: >-
            This configuration allows you to configure RDMA flow over the same QP number from same source and destination.
      type: object
      properties:
        source_qp_number:
          description: >-
            Configure the QP range.
          type: integer
          format: uint32
          default: 2
          minimum: 2
          maximum: 33554431
          x-field-uid: 1
        dscp:
          description: >-
            DSCP value for this flow
          type: integer
          format: uint32
          default: 24
          minimum: 0
          maximum: 63
          x-field-uid: 2
        ecn:
          description: >-
            This field allows to configure bits of the Traffic Class field in the IPv4 or IPv6 header to encode four different code points.
          type: integer
          format: uint32
          default: 1
          minimum: 0
          maximum: 3
          x-field-uid: 3
        udp_source_port:
          description: >-
            UDP source port number for this flow.
          type: integer
          format: uint32
          default: 49152
          minimum: 0
          maximum: 65535
          x-field-uid: 4
        rocev2_verb:
          description: >-
            RoCEv2 Verb, Available options are: none, write, wrtie_with_immediate, send, send_with_immediate and read: The corresponding flow will not take part in traffic.
          type: string
          default: write
          x-enum:
            none:
              x-field-uid: 1
            write:
              x-field-uid: 2
            write_with_immediate:
              x-field-uid: 3
            send:
              x-field-uid: 4
            send_with_immediate:
              x-field-uid: 5
            read:
              x-field-uid: 6
          x-field-uid: 5
        immediate_data:
          description: >-
            Immediate Data field required for SEND/WRITE with immediate verb.
          type: string
          format: hex
          default: "00000000"
          x-field-uid: 6
        message_size:
          description: >-
            The Maximum message size that is allowed to transfer depends on the MTU size and the number of VLANs configured on the interfaces.
          type: integer
          format: uint32
          default: 1
          minimum: 0
          maximum: 65535
          x-field-uid: 7
        message_size_unit:
          description: >-
            Unit of the transfer message size. Available options are Bytes, KB, MB.
          type: string
          default: MB
          x-enum:
            Byte:
              x-field-uid: 1
            KB:
              x-field-uid: 2
            MB:
              x-field-uid: 3
            GB:
              x-field-uid: 4
          x-field-uid: 8
    