components:
  schemas:
    RoCEv2.FlowSettings:
      description: >-
            This configuration allows you to configure RDMA flow over the same QP number from same source and destination.
      type: object
      properties:
        connection_type:
          description: >-
            There are multiple connection types. Valid values are :  Reliable Connection (RC), Reliable Datagram (RD), Extended Reliable Connection (XRC),
            Unreliable Datagram (UD),  Unreliable Connection (UC), Raw IPv6 Datagram, Raw Ethertype Datagram.
          type: string
          x-enum:
            reliable_connection:
              x-field-uid: 1
            reliable_datagram:
              x-field-uid: 2
            extended_reliable_connection:
              x-field-uid: 3
            unreliable_datagram:
              x-field-uid: 4
            unreliable_connection:
              x-field-uid: 5
            raw_ipv6_datagram:
              x-field-uid: 6
            raw_ethernet_datagram:
              x-field-uid: 7
          x-field-uid: 1
        source_qp_number:
          description: >-
            Configure the QP range.
          type: integer
          format: uint32
          default: 2
          minimum: 2
          maximum: 33554431
          x-field-uid: 2
        dscp:
          description: >-
            DSCP value for this flow
          type: integer
          format: uint32
          default: 24
          minimum: 0
          maximum: 63
          x-field-uid: 3
        ecn:
          description: >-
            This field allows to configure bits of the Traffic Class field in the IPv4 or IPv6 header to encode four different code points.
          type: integer
          format: uint32
          default: 1
          minimum: 0
          maximum: 3
          x-field-uid: 4
        udp_source_port:
          description: >-
            UDP source port number for this flow.
          type: integer
          format: uint32
          default: 49152
          minimum: 0
          maximum: 65535
          x-field-uid: 5
        rocev2_verb:
          description: >-
            RoCEv2 Verb, Available options are: none, write, wrtie_with_immediate, send, send_with_immediate and read: The corresponding flow will not take part in traffic.
          type: string
          default: write
          x-enum:
            none:
              x-field-uid: 1
            write:
              x-field-uid: 2
            write_with_immediate:
              x-field-uid: 3
            send:
              x-field-uid: 4
            send_with_immediate:
              x-field-uid: 5
            read:
              x-field-uid: 6
          x-field-uid: 6
        immediate_data:
          description: >-
            Immediate Data field required for SEND/WRITE with immediate verb.
          type: string
          format: hex
          default: "00000000"
          x-field-uid: 7
        message_size:
          description: >-
            The Maximum message size that is allowed to transfer depends on the MTU size and the number of VLANs configured on the interfaces.
          type: integer
          format: uint32
          default: 1
          minimum: 0
          maximum: 65535
          x-field-uid: 8
        message_size_unit:
          description: >-
            Unit of the transfer message size. Available options are Bytes, KB, MB.
          type: string
          default: MB
          x-enum:
            Byte:
              x-field-uid: 1
            KB:
              x-field-uid: 2
            MB:
              x-field-uid: 3
            GB:
              x-field-uid: 4
          x-field-uid: 9
        dcqcn_settinga:
          $ref: '#/components/schemas/RoCEv2.DCQCN'
          x-field-uid: 10
    RoCEv2.DCQCN:
      description: |-
        RoCEv2 DCQCN Settings.
      type: object
      properties:
        alpha_g:
          description: |-
            Alpha G.
          type: integer
          format: uint64
          x-field-uid: 1
        initial_alpha:
          description: |-
            Initial Alpha.
          type: integer
          format: uint64
          x-field-uid: 2
        alpha_update_period:
          description: |-
            Alpha Update period in microseconds.
          type: integer
          format: uint64
          x-field-uid: 3
        rate_reduction_time_period:
          description: |-
            Rate reduction time period in microseconds.
          type: integer
          format: uint64
          x-field-uid: 4
        initial_rate_after_first_cnp:
          description: |-
            initial rate after first CNP in Percentage.
          type: integer
          format: uint32
          minimum: 0
          maximum: 100
          x-field-uid: 5
        minimum_rate_limmit:
          description: |-
            Minimum Rate Limit in Percentage.
          type: integer
          format: uint32
          minimum: 0
          maximum: 100
          x-field-uid: 6
        maximum_rate_decrement_at_time:
          description: |-
            Maximum rate decrement at time in Percentage.
          type: integer
          format: uint32
          minimum: 0
          maximum: 100
          x-field-uid: 7
        clamp_target_rate:
          description: |-
            Clamp Target rate.
          type: boolean
          x-field-uid: 8
        rate_increment_time:
          description: |-
            Rate increment time period in microseconds.
          type: integer
          format: uint64
          x-field-uid: 9
        rate_increment_byte_counter:
          description: |-
            Rate increment byte counter in uint 64 bytes.
          type: integer
          format: uint64
          x-field-uid: 10
        rate_increment_threshold:
          description: |-
            Rate increment threshold.
          type: integer
          format: uint32
          minimum: 1
          maximum: 31
          x-field-uid: 11
        additive_increment_rate:
          description: |-
            additive increment rate in Percentage.
          type: integer
          format: uint32
          minimum: 0
          maximum: 100
          x-field-uid: 12
        hyper_increment_rate:
          description: |-
            hyper increment rate in Percentage.
          type: integer
          format: uint32
          minimum: 0
          maximum: 100
          x-field-uid: 13

    