components:
  schemas:
    App:
      description: >-
        A container for emulated protocol and traffic configuration.
      type: object
      properties:
        tcp:
          description: >-
            The properties of TCP and its children, 
          type: array
          items:
            $ref: './tcp/tcp.yaml#/components/schemas/App.Tcp'  
          x-field-uid: 1
        http:
          description: >-
            The properties of HTTP and its children, 
          type: array
          items:
            $ref: './http/http.yaml#/components/schemas/App.Http'
          x-field-uid: 2
        ssl:
          description: >-
            IPv4 Loopback interface that can be attached to an Ethernet in the same
            device  or to an Ethernet in another device.
          type: array
          items:
            $ref: './ssl/ssl.yaml#/components/schemas/App.Ssl'
          x-field-uid: 3
        traffic:
          description: >-
            Ethernet configuration for one or more emulated network interfaces.
          type: array
          items:
            $ref: './traffic/traffic.yaml#/components/schemas/App.Traffic'
          x-field-uid: 4
        name:
          x-include: ../common/common.yaml#/components/schemas/Named.Object/properties/name
          x-field-uid: 5
      required: [name]