components:
  schemas:
    App:
      description: >-
        A container for emulated TCP/UDP , application protocols, attacks and it's traffic configurations.
      type: object
      properties:
        tcp:
          description: >-
            The properties of TCP and its children, 
          type: array
          items:
            $ref: './tcp/tcp.yaml#/components/schemas/App.Tcp'  
          x-field-uid: 1
        http_client:
          description: >-
            The properties of HTTP client, 
          type: array
          items:
            $ref: './http/httpclient.yaml#/components/schemas/App.HttpClient'
          x-field-uid: 2
        http_server:
          description: >-
            The properties of HTTP server, 
          type: array
          items:
            $ref: './http/httpserver.yaml#/components/schemas/App.HttpServer'
          x-field-uid: 3
        ssl:
          description: >-
            SSL configuration
          type: array
          items:
            $ref: './ssl/ssl.yaml#/components/schemas/App.Ssl'
          x-field-uid: 4
        stateful_flows:
          description: >-
            Traffic configuration of endpoints.
          type: array
          items:
            $ref: './statefull_flow/statefulflow.yaml#/components/schemas/StatefulFlow'
          x-field-uid: 5
        name:
          x-include: ../common/common.yaml#/components/schemas/Named.Object/properties/name
          x-field-uid: 6
      required: [name]