components:
  schemas:
    CaptureSettings:
      description: The capture settings for an agent
      properties:
        captureenabled:
          description: 'The enable status of the capture configuration (default: false).'
          type: boolean
          x-field-uid: 1
        capturelatestpackets:
          default: true
          description: Capture first or latest packets (true to enable latest packets
            capture).
          type: boolean
          x-field-uid: 2
        loglevel:
          $ref: ../loglevel/loglevel.yaml#/components/schemas/LogLevel
          description: 'Log level options: NONE, ERROR, WARN, INFO, DEBUG, TRACE (default:
            INFO)'
          x-field-uid: 3
        maxcapturesize:
          default: 104857600
          description: 'The maximum capture size in bytes (default: 104857600).'
          format: int64
          type: integer
          x-field-uid: 4
      required:
      - captureenabled
      - loglevel
      type: object
