components:
  schemas:
    ApplicationProfile:
      description: The configuration for DUT
      properties:
        active:
          x-field-uid: 12
          x-include: ../trafficprofilebase/trafficprofilebase.yaml#/components/schemas/TrafficProfileBase/properties/active
        add_applications:
          items:
            $ref: ../externalresourceinfo/externalresourceinfo.yaml#/components/schemas/ExternalResourceInfo
          type: array
          x-field-uid: 5
        applications:
          items:
            $ref: ../application/application.yaml#/components/schemas/Application
          type: array
          x-field-uid: 1
        defaultnetworkmapping:
          $ref: ../networkmapping/networkmapping.yaml#/components/schemas/NetworkMapping
          x-field-uid: 2
        modify_excluded_dut_recursively:
          items:
            $ref: ../updatenetworkmapping/updatenetworkmapping.yaml#/components/schemas/UpdateNetworkMapping
          type: array
          x-field-uid: 7
        modify_tags_recursively:
          items:
            $ref: ../updatenetworkmapping/updatenetworkmapping.yaml#/components/schemas/UpdateNetworkMapping
          type: array
          x-field-uid: 8
        name:
          type: string
          x-field-uid: 3
        objectivesandtimeline:
          $ref: ../objectivesandtimeline/objectivesandtimeline.yaml#/components/schemas/ObjectivesAndTimeline
          x-field-uid: 4
        reset_tags_to_default:
          items:
            format: byte
            type: string
          type: array
          x-field-uid: 9
        trafficsettings:
          x-field-uid: 13
          x-include: ../trafficprofilebase/trafficprofilebase.yaml#/components/schemas/TrafficProfileBase/properties/trafficsettings
      required:
      - name
      type: object
