components:
  schemas:
    Config.Append:
      description: |-
        A container for all models that are part of the configuration.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            devices:
              x-field-uid: 1
            ethernets:
              x-field-uid: 2
            flows:
              x-field-uid: 3
            lldp:
              x-field-uid: 4
          x-field-uid: 1
        parent:
          description: |-
            The unique parent name under which the configuration resource will be added.
            For resource types devices, flows and lldp the parent will be empty string.
            For resource types like ethernet the parent will be the device name.
          type: string
          x-field-uid: 2
        devices:
          description: |-
            The emulated devices that will be added to existing configuration on the traffic generator.
            The device name must not already be used in existing configuration.
          type: array
          items:
            $ref: '../device/device.yaml#/components/schemas/Device'
          x-field-uid: 3
        ethernets:
          description: |-
            Ethernet configuration for one or more emulated or simulated network interfaces.
            The ethernet name must not already be used in existing configuration.
          type: array
          items:
            $ref: './ethernet.yaml#/components/schemas/Device.Ethernet'
          x-field-uid: 4
        flows:
          description: |-
            The flows that will be added to existing configuration on the traffic generator.
            The flow name must not already be used in existing configuration.
          type: array
          items:
            $ref: '../flow/flow.yaml#/components/schemas/Flow'
          x-field-uid: 5
        lldp:
          description: |-
            LLDP protocol that will be configured on traffic generator. The lldp name must not already
            be used in existing configuration.
          type: array
          items:
            $ref: '../lldp/lldp.yaml#/components/schemas/Lldp'
          x-field-uid: 6