components:
  schemas:
    Config.Append:
      description: |-
        A container for all configuration resources of various types to be appended.
      properties:
        resources:
          description: |-
            Configuration resources of various types to be appended.
          type: array
          items:
            $ref: '#/components/schemas/Config.AppendResource'
          x-field-uid: 1
    Config.AppendResource:
      description: |-
        A container for an existing resource to be appended.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            flows:
              x-field-uid: 1
          x-field-uid: 1
        flows:
          description: |-
            The flows that will be added to existing configuration on the traffic generator.
            The flow name must not already be used in existing configuration.
          type: array
          items:
            $ref: '../flow/flow.yaml#/components/schemas/Flow'
          x-field-uid: 2