components:
  schemas:
    Config.Append:
      description: |-
        A container for all models that are part of the configuration.
      type: object
      properties:
        devices:
          description: |-
            The emulated devices that will be configured on the traffic generator.
            Each device contains configurations for network interfaces and 
            protocols running on top of those interfaces.
          type: array
          items:
            $ref: '../device/device.yaml#/components/schemas/Device'
          x-field-uid: 1
        flows:
          description: |-
            The flows that will be configured on the traffic generator.
          type: array
          items:
            $ref: '../flow/flow.yaml#/components/schemas/Flow'
          x-field-uid: 2
        lldp:
          description: |-
            LLDP protocol that will be configured on traffic generator.
          type: array
          items:
            $ref: '../lldp/lldp.yaml#/components/schemas/Lldp'
          x-field-uid: 3