components:
  schemas:
    Config.Artifacts:
      $ref: '../common/common.yaml#/components/schemas/Placeholder.Object'
      description: >-
        Artifacts storage configuration.
        PLACEHOLDER: configuration schema is not yet defined.
