components:
  schemas:
    Config.Delete:
      description: |-
        A container for all models that are part of the configuration.
      type: object
      properties:
        devices:
          description: |-
            List of devices that will be deleted from configuration on the traffic generator.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Device/properties/name'
          x-field-uid: 1
        flows:
          description: |-
            List of flows that will be deleted from configuration on the traffic generator.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Flow/properties/name'
          x-field-uid: 2
        lldps:
          description: |-
            List of LLDP protocols that will be deleted from configuration on the traffic generator.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Lldp/properties/name'
          x-field-uid: 3