components:
  schemas:
    Config.Delete:
      description: |-
        A container for all models that are part of the configuration.
      type: object
      properties:
        choice:
          type: string
          x-enum:
            devices:
              x-field-uid: 1
            ethernets:
              x-field-uid: 2
            flows:
              x-field-uid: 3
            lldp:
              x-field-uid: 4
          x-field-uid: 1
        resource_names:
          description: |-
            List of resources of specified type that will be deleted from existing configuration on the traffic generator.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Device/properties/name'
          - '/components/schemas/Device.Ethernet/properties/name'
          - '/components/schemas/Flow/properties/name'
          - '/components/schemas/Lldp/properties/name'
          x-field-uid: 2