components:
  schemas:
    Config.Delete:
      description: |-
        A container for all configuration resources of various types to be deleted.
      type: array
      items:
        $ref: '#/components/schemas/Config.DeleteResource'
      x-field-uid: 1
    Config.DeleteResource:
      description: |-
        A container for an existing resource to be deleted.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            devices:
              x-field-uid: 1
            ethernets:
              x-field-uid: 2
            flows:
              x-field-uid: 3
            lldp:
              x-field-uid: 4
          x-field-uid: 1
        devices:
          description: |-
            List of resources of specified type that will be deleted from existing configuration on the traffic generator.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Device/properties/name'
          x-field-uid: 2
        ethernets:
          description: |-
            List of ethernets that will be deleted from existing configuration on the traffic generator.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Device.Ethernet/properties/name'
          x-field-uid: 3
        flows:
          description: |-
            List of flows that will be deleted from existing configuration on the traffic generator.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Flow/properties/name'
          x-field-uid: 4
        lldp:
          description: |-
            List of LLDP protocols that will be deleted from existing configuration on the traffic generator.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Lldp/properties/name'
          x-field-uid: 5