components:
  schemas:
    Config.Delete:
      description: |-
        A container for all configuration resources of various types to be deleted.
      type: array
      items:
        $ref: '#/components/schemas/Config.DeleteResource'
      x-field-uid: 1
    Config.DeleteResource:
      description: |-
        A container for an existing resource to be deleted.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            flows:
              x-field-uid: 1
          x-field-uid: 1
        flows:
          description: |-
            List of flows that will be deleted from existing configuration on the traffic generator.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Flow/properties/name'
          x-field-uid: 2