openapi: 3.0.3
info:
  title: Control protocol models for devices update
  description: >-
    All control protocol schemas for devices update
  version: ^0.0.0
components:
  schemas:
    Update.Device.Bgp:
      description: >-
        Updates properties of configured BGP
      type: object
      required:
        - property_names
        - bgp
      properties:
        property_names:
          description: >-
            BGP properties to be updated.
          type: array
          items:
            type: string
            x-enum:
              peer_enabled:
                x-field-uid: 1
          x-field-uid: 1
        bgp:
          description: >-
            The list of configured BGP peers for which given property will be updated.
          type: array
          items:
            $ref: '#/components/schemas/Device.BgpRouter'
          x-field-uid: 2