components:
  schemas:
    Config.Generate.Request:
      description: |-
        A configuration that describes a set of new resources to be generated.
      type: object
      required: [choice]
      properties:
        choice:
          type: string
          x-enum:
            collective_communications:
              x-field-uid: 1
          x-field-uid: 1
        collective_communications:
          description: |-
            The inputs used to generate a Collective Communication Benchmarks
            configuration, including the infrastructure the benchmark will run on.
          $ref: '../collective_communications/generate.yaml#/components/schemas/CollectiveCommunications.Config.Generate.Request'
          x-field-uid: 2

