components:
  schemas:
    Config.Update:
      description: >-
        Request for updating specific attributes of resources in traffic generator
      type: object
      properties:
        choice:
          type: string
          x-enum:
            flows:
              x-field-uid: 1
          x-field-uid: 1
        flows:
          $ref: '#/components/schemas/Flows.Update'
          x-field-uid: 2
        protocols:
          $ref: '#/components/schemas/Protocols.Update'
          x-field-uid: 3
    Flows.Update:
      description: >-
        A container of flows with associated properties to be updated without
        affecting the flows current transmit state.
      type: object
      required:
        - property_names
        - flows
      properties:
        property_names:
          description: >-
            Flow properties to be updated without affecting the transmit state.
          type: array
          items:
            type: string
            x-enum:
              rate:
                x-field-uid: 1
              size:
                x-field-uid: 2
          x-field-uid: 1
        flows:
          description: >-
            The list of configured flows for which given property will be updated.
          type: array
          items:
            $ref: '#/components/schemas/Flow'
          x-field-uid: 2
    Protocols.Update:
      description: >-
        Protocols for which update properties would be initiated.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            bgp:
              x-field-uid: 1
          x-field-uid: 1
        bgp:
          $ref: './protocol.yaml#/components/schemas/Update.Protocol.Bgp'
          x-field-uid: 2