openapi: 3.0.3
info:
  title: Update protocol Config
  description: >-
    Update protocol Config for all control protocol schemas
  version: ^0.0.0
components:
  schemas:
    UpdateProtocol.Config.Isis:
      description: >-
        A container of IS-IS with associated properties to be updated that may or may not
        able to maintain the current IS-IS Up session state always.
      type: object
      properties:
        links:
          description: >-
            The list of IS-IS emulated or simulated interfaces with associated properties to be updated.
          type: array
          items:
            $ref: '#/components/schemas/UpdateProtocol.Config.Isis.Link'
          x-field-uid: 1

    UpdateProtocol.Config.Isis.Link:
      description: >-
        A container of IS-IS with associated properties to be updated that may or may not
        able to maintain the current IS-IS Up session state always.
      type: object
      properties:
        interface_name:
          description: >-
            The name of an IS-IS emulated or simulated interface.
          type: string
          x-constraint:
          - "/components/schemas/Isis.Interface/properties/name"
          x-field-uid: 1
        metric:
          description: >-
            If IS-IS session will be flapped if the link metric is updated on a emullated interface. 
            However, if the link metric is updated on a simulated interface then IS-IS session will be maintained in Up state.
            There will be LSP update with new metric value sent to the neighbors.
          type: integer
          format: uint32
          maximum: 16777215
          default: 10
          x-field-uid: 2
   