openapi: 3.0.3
info:
  title: Control action models
  description: >-
    All control action schemas
  version: ^0.0.0
components:
  schemas:
    Control.Action.Request:
      description: >-
        Request for triggering action on resources in traffic generator
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            ping:
              x-field-uid: 1
          x-field-uid: 1
        ping:
          $ref: './ping.yaml#/components/schemas/Ping.Request'
          x-field-uid: 2
    Control.Action.Response:
      description: >-
        Response upon triggering action on resources in traffic generator
      type: object
      properties:
        choice:
          type: string
          x-enum:
            ping:
              x-field-uid: 1
          x-field-uid: 1
        ping:
          $ref: './ping.yaml#/components/schemas/Ping.Response'
          x-field-uid: 2