# openapi: 3.0.3
# info:
#   title: Control action models
#   description: >-
#     All control action schemas
#   version: ^0.0.0
# components:
#   schemas:
#     Control.Action:
#       description: >-
#         Request for performing action against resources configured in traffic generator
#       type: object
#       required:
#         - choice
#       properties:
#         choice:
#           type: string
#           x-enum:
#             protocol:
#               x-field-uid: 1
#           x-field-uid: 1
#         protocol:
#           $ref: '#/components/schemas/Action.Protocol'
#           x-field-uid: 2
#     Control.Action.Response:
#       description: >-
#         Responses for action against resources configured in traffic generator
#       type: object
#       required:
#         - choice
#       properties:
#         choice:
#           type: string
#           x-enum:
#             protocol:
#               x-field-uid: 1
#           x-field-uid: 1
#         protocol:
#           $ref: '#/components/schemas/Action.Protocol.Response'
#           x-field-uid: 2
#     Action.Protocol:
#       description: >-
#         Actions associated with protocols configured on resources in traffic generator
#       type: object
#       required:
#         - choice
#       properties:
#         choice:
#           type: string
#           x-enum:
#             ipv4:
#               x-field-uid: 1
#             ipv6:
#               x-field-uid: 2
#           x-field-uid: 1
#         ipv4:
#           $ref: './ipv4.yaml#/components/schemas/Action.Protocol.Ipv4'
#           x-field-uid: 2
#         ipv6:
#           $ref: './ipv6.yaml#/components/schemas/Action.Protocol.Ipv6'
#           x-field-uid: 3
#     Action.Protocol.Response:
#       description: >-
#         Responses for actions associated with protocols configured on resources in traffic generator
#       type: object
#       required:
#         - choice
#       properties:
#         choice:
#           type: string
#           x-enum:
#             ipv4:
#               x-field-uid: 1
#             ipv6:
#               x-field-uid: 2
#           x-field-uid: 1
#         ipv4:
#           $ref: './ipv4.yaml#/components/schemas/Action.Protocol.Ipv4.Response'
#           x-field-uid: 2
#         ipv6:
#           $ref: './ipv6.yaml#/components/schemas/Action.Protocol.Ipv6.Response'
#           x-field-uid: 3