openapi: 3.0.3
info:
  title: Control action models
  description: >-
    All control action schemas
  version: ^0.0.0
components:
  schemas:
    Control.Action:
      description: >-
        Request for triggering action against configured resources.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            protocol:
              x-field-uid: 1
          x-field-uid: 1
        protocol:
          $ref: '#/components/schemas/Action.Protocol'
          x-field-uid: 2
    Control.Action.Response:
      description: >-
        Response for action triggered against configured resources along with warnings.
      type: object
      properties:
        warnings:
          description: List of warnings generated while triggering specified action
          type: array
          items:
            type: string
          x-field-uid: 1
        response:
          $ref: '#/components/schemas/Action.Response'
          x-field-uid: 2
    Action.Response:
      description: >-
        Response for action triggered against configured resources.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            protocol:
              x-field-uid: 1
          x-field-uid: 1
        protocol:
          $ref: '#/components/schemas/Action.Response.Protocol'
          x-field-uid: 2
    Action.Protocol:
      description: >-
        Actions associated with protocols on configured resources.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            ipv4:
              x-field-uid: 1
            ipv6:
              x-field-uid: 2
            bgp:
              x-field-uid: 3
          x-field-uid: 1
        ipv4:
          $ref: './ipv4.yaml#/components/schemas/Action.Protocol.Ipv4'
          x-field-uid: 2
        ipv6:
          $ref: './ipv6.yaml#/components/schemas/Action.Protocol.Ipv6'
          x-field-uid: 3
        bgp:
          $ref: './bgp.yaml#/components/schemas/Action.Protocol.Bgp'
          x-field-uid: 4
        isis:
          $ref: './isis.yaml#/components/schemas/Action.Protocol.Isis'
          x-field-uid: 5
          
    Action.Response.Protocol:
      description: >-
        Response for actions associated with protocols on configured resources.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            ipv4:
              x-field-uid: 1
            ipv6:
              x-field-uid: 2
          x-field-uid: 1
        ipv4:
          $ref: './ipv4.yaml#/components/schemas/Action.Response.Protocol.Ipv4'
          x-field-uid: 2
        ipv6:
          $ref: './ipv6.yaml#/components/schemas/Action.Response.Protocol.Ipv6'
          x-field-uid: 3