openapi: 3.1.0

info:
  title: Action models
  description: >-
    All Detail Action schemas
  version: ^0.0.0

components:
  schemas:
    Lacp.Action.Request:
      description: >-
        Request to traffic generator for choice of action on LACP protocol
      type: object
      properties:
        choice:
          type: string
          enum:
          - set_transmission_state
        set_transmission_state:
          $ref: '#/components/schemas/Lacp.Transmission.State'

    Lacp.Transmission.State:
      description: >-
        Set LACP PDU transmission state for LAG Member Port.
      type: object
      required: [state]
      properties:
        port_names:
          description: >-
            The names of LAG member port objects to control.
            An empty or null list will control all LAG member port objects.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Port/properties/name'
        state:
          description: >-
            The LACP PDU Transmission state.
            'start' will start transmission of PDUs on selected member ports.
            'stop' will stop transmission of PDUs on selected member ports.
          type: string
          enum: [start, stop]