openapi: 3.0.3
info:
  title: Control traffic models
  description: >-
    All control traffic schemas
  version: ^0.0.0
components:
  schemas:
    State.App.State:
      description: >-
        Provides state control of app traffic.
      type: object
      required:
        - state
      properties:
        state:
          description: >-
            The transmit state.

            If the value of the state property is 'start' then all flows
            defined by the 'flow_names' property will be started and the metric
            counters MUST be cleared prior to starting the flow(s).

            If the value of the state property is 'stop' then all flows
            defined by the 'flow_names' property will be stopped and the metric
            counters MUST NOT be cleared.

            If the value of the state property is 'pause' then all flows
            defined by the 'flow_names' property will be paused and the metric
            counters MUST NOT be cleared.

            If the value of the state property is 'resume' then any paused flows
            defined by the 'flow_names' property will start transmit at the
            point at which they were paused. Any flow that is stopped will
            start transmit at the beginning of the flow.
            The flow(s) MUST NOT have their metric counters cleared.
          type: string
          x-field-uid: 1
          x-enum:
            start:
              x-field-uid: 1
            stop:
              x-field-uid: 2
            pause:
              x-field-uid: 3