openapi: 3.0.3
info:
  title: BGP Control models
  description: >-
    All BGP control schemas
  version: ^0.0.0
components:
  schemas:
    Action.Protocol.Bgp:
      description: >-
        Actions associated with BGP on configured resources.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            notification:
              x-field-uid: 1
            initiate_graceful_restart:
              x-field-uid: 2
            import_routes:
              x-field-uid: 3
          x-field-uid: 1
        notification:
          $ref: "#/components/schemas/Action.Protocol.Bgp.Notification"
          x-field-uid: 2
        initiate_graceful_restart:
          $ref: "#/components/schemas/Action.Protocol.Bgp.InitiateGracefulRestart"
          x-field-uid: 3
        import_routes:
          $ref: "#/components/schemas/Action.Protocol.Bgp.ImportRoutes"
          x-field-uid: 4

    Action.Protocol.Bgp.Notification:
      description: >-
        A NOTIFICATION message is sent when an error is detected with the BGP session, such as hold timer expiring, misconfigured AS number 
        or a BGP session reset is requested. This causes the BGP connection to close. Send explicit NOTIFICATIONs for list of specified 
        BGP peers. If a user wants to send custom Error Code and Error Subcode the custom object should be configured.
        A user can send IANA defined BGP NOTIFICATIONs according to https://www.iana.org/assignments/bgp-parameters/bgp-parameters.xhtml. 
      type: object
      properties:
        names:
          description: >-
            The names of BGP Peers to send NOTIFICATION to. If no name is specified then NOTIFICATION will be sent to all configured BGP peers.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Device.Bgp/properties/name'
          x-field-uid: 1
        choice:
          description: >-
            Each BGP NOTIFICATION message includes an Error Code field indicating what type of problem occurred. For certain Error Codes, an Error 
            Subcode field provides additional details about the specific nature of the problem. 
            The choice value will provide the Error Code used in NOTIFICATION message. 
            The Subcode can be set for each of the corresponding errors except for Hold Timer Expired error and BGP Finite State Machine error. 
            In both of these cases Subcode 0 will be sent. If a user wants to use non zero Sub Code then custom choice can be used.
          type: string
          x-field-uid: 2
          default: cease
          x-enum:
            cease:
              x-field-uid: 1
            message_header_error:
              x-field-uid: 2
            open_message_error:
              x-field-uid: 3
            update_message_error:
              x-field-uid: 4
            hold_timer_expired:
              x-field-uid: 5
            finite_state_machine_error:
              x-field-uid: 6
            custom:
              x-field-uid: 7

        cease:
          $ref: '#/components/schemas/Device.Bgp.CeaseError'
          x-field-uid: 3 
        message_header_error:
          $ref: '#/components/schemas/Device.Bgp.MessageHeaderError'
          x-field-uid: 4 
        open_message_error:
          $ref: '#/components/schemas/Device.Bgp.OpenMessageError'
          x-field-uid: 5 
        update_message_error:
          $ref: '#/components/schemas/Device.Bgp.UpdateMessageError'
          x-field-uid: 6 
        hold_timer_expired:
          $ref: '#/components/schemas/Device.Bgp.HoldTimerExpired'
          x-field-uid: 7
        finite_state_machine_error:
          $ref: '#/components/schemas/Device.Bgp.FiniteStateMachineError'
          x-field-uid: 8
        custom:
          $ref: '#/components/schemas/Device.Bgp.CustomError'
          x-field-uid: 9

    Action.Protocol.Bgp.InitiateGracefulRestart:
      description: >-
        Initiates BGP Graceful Restart process for the selected BGP peers.
        If no name is specified then Graceful Restart will be sent to all configured BGP peers.
      type: object
      properties:
        peer_names:
          description: >-
            The names of device BGP peers objects to control.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Device.Bgp/properties/name'
          x-field-uid: 1
        restart_delay:
          description: |-
            Duration (in seconds) after which selected BGP peers will initiate 
            Graceful restart by sending the Open Message with Restart State bit set in the Graceful Restart capability.
          type: integer
          format: uint32
          maximum: 3600
          default: 30
          x-field-uid: 2

    Action.Protocol.Bgp.ImportRoutes:
      description: |-
        Import V4 and V6 routes installed on and exported from a DUT,
        the format for which could be different across vendors, and convert
        those to OTG V4 or V6 routes configured across corresponding BGP peers.
        Following additional details need to be considered:
        - The exported routes may be provided in variety of file formats
        - A given file may contain both V4 and V6 route entries
        - Each route entry shall correspond to `Bgp.V4RouteRange` or `Bgp.V6RouteRange`
          with exactly one entry of `V4RouteAddress` or `V6RouteAddress` respectively
        - The name of resultant OTG V4 or V6 routes shall be a constituent of
          an alias associated with import file, name of corresponding BGP peer
          and the sequence number corresponding to its order of entry in the file
      type: object
      properties:
        imports:
          type: array
          items:
            $ref: '#/components/schemas/Action.Protocol.Bgp.RouteImport'
          x-field-uid: 1

    Action.Protocol.Bgp.RouteImport:
      description: >-
        Configuration for specifying the format and corresponding characteristics
        of V4 or V6 routes to be imported.
      type: object
      required: 
        -  name
      properties:
        name:
          x-include: ../common/common.yaml#/components/schemas/Named.Object/properties/name
          x-field-uid: 1
        routes:
          $ref: '#/components/schemas/Action.Protocol.Bgp.Routes'
          x-field-uid: 2
        targets:
          description: |-
            List of import targets (i.e. corresponding V4 or V6 route groups) and
            associated import properties
          type: array
          items: 
            $ref: '#/components/schemas/Action.Protocol.Bgp.RouteImport.Target'
          x-field-uid: 3

    Action.Protocol.Bgp.Routes:
      description: >-
        Routes to be imported in a given format.
      type: object
      properties:
        choice:
          description: Format of routes to be imported.
          type: string
          x-field-uid: 1
          x-enum:
            v4_routes:
              x-field-uid: 1
            v6_routes:
              x-field-uid: 2
            openconfig_routes:
              x-field-uid: 3
            cisco_routes:
              x-field-uid: 4
            juniper_routes:
              x-field-uid: 5
        v4_routes:
          type: array
          items:
            $ref: '../device/bgp/bgpv4routerange.yaml#/components/schemas/Bgp.V4RouteRange'
          x-field-uid: 2
        v6_routes:
          type: array
          items:
            $ref: '../device/bgp/bgpv6routerange.yaml#/components/schemas/Bgp.V6RouteRange'
          x-field-uid: 3
        openconfig_routes:
          description: |-
            Binary containing routes in OpenConfig format
          type: string
          format: binary
          x-field-uid: 4
        cisco_routes:
          description: |-
            Binary containing routes in Cisco format
          type: string
          format: binary
          x-field-uid: 5
        juniper_routes:
          description: |-
            Binary containing routes in Juniper format
          type: string
          format: binary
          x-field-uid: 6

    Action.Protocol.Bgp.RouteImport.Target:
      description: >-
        Import target (i.e. corresponding V4 or V6 route group) and associated
        import properties
      type: object
      required: 
        -  route_group_name
      properties:
        route_group_name:
          description: |-
            The names of configured V4 or V6 route group
          type: string
          x-constraint:
            - '/components/schemas/Bgp.V4RouteGroup/properties/name'
            - '/components/schemas/Bgp.V6RouteGroup/properties/name'
          x-field-uid: 1
        use_best_routes:
          description: |-
            When set to false, all routes available shall be advertised.
          type: boolean
          default: true
          x-field-uid: 2
        retain_next_hop:
          description: |-
            When set to false, the next hop address present against each route to be advertised
            is replaced with next hop address of the corresponding test port.
          type: boolean
          default: false
          x-field-uid: 3