openapi: 3.0.3
info:
  title: BGP Graceful Restart Control models
  description: >-
    BGP Graceful Restart Control schemas
  version: ^0.0.0
components:
  schemas:  
    Bgp.GraceFulRestart:
      description: >-
        Initiates BGP Graceful Restart process for the selected BGP peers.
      type: object
      properties:
        peer_names:
          description: >-
            The names of device BGP peer objects to control.
            If no names are specified then all BGP peer objects that match the
            x-constraint will be affected.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Device.Bgp/properties/name'
          x-field-uid: 1
        restart_time:
          description: >-
            This is the time (in seconds) after which the selected BGP peers will initiate the 
            Graceful restart by sending the Open Message with Restart bit set.
          type: integer
          format: uint32
          maximum: 3600
          default: 30
          x-field-uid: 2