openapi: 3.0.3
info:
  title: Control AI Workload executions
  description: >-
    Control AI Workload executions
  version: ^0.0.0
components:
  schemas:
    State.CollectiveCommunications.Execution:
      description: >-
        Provides state control of AI Workload executions. AI workloads typically run through a number of
        states until they reach a terminal state, but can end prematurely if an error is encountered, or
        if the user requests a stop.
      type: object
      required:
        - state
      properties:
        state:
          description: |-
            The requested AI workload execution state.

            If the value of the state property is 'start' then the AI workload will be run, if possible.

            If the value of the state property is 'stop' then the AI workload will be stopped before automatically
            completing. Normally the AI workload will automatically stop when all the requested combinations have
            been executed, so this is not normally needed.
          type: string
          x-field-uid: 1
          x-enum:
            start:
              x-field-uid: 1
            stop:
              x-field-uid: 2
