openapi: 3.1.0

info:
  title: Control models
  description: >-
    All control schemas
  version: ^0.0.0

components:
  schemas:
    Control.Action:
      description: >-
        One or more control actions to be performed against intended resources.
      type: object
      properties:
        flow_names:
          description: >-
            The names of flows to apply control actions on.
            An empty list will apply control actions on all flows.
          type: array
          items:
            type: string
            x-constraint:
            - '/components/schemas/Flow/properties/name'
        port_names:
          description: >-
            The names of ports to apply control actions on.
            An empty list will apply control actions on all ports.
          type: array
          items:
            type: string
            x-constraint:
            - '/components/schemas/Port/properties/name'
        actions:
          description: >-
            List of control actions. The actions prefixed with `o_` are granular actions.
          type: array
          items:
            type: string
            enum:
              - start
              - stop
              - pause
              - resume
              - update
              - o_connect
              - o_disconnect
              - o_update_layer1
              - o_start_transmit
              - o_stop_transmit
              - o_start_capture
              - o_stop_capture
              - o_clear_stats
              - o_start_devices
              - o_stop_devices

    Control.Status:
      description: >-
        Status of all supported control actions. Whenever a control action is
        requested, its status is reset to `none` and updated to `done` or `failed`
        only when the underlying operations associated with it succeeds or fails
        respectively. The details of failure for a given action can be found in
        list of errors.
      type: object
      properties:
        start:
          description: >-
            Indicates whether traffic run has been successfully started.
          type: string
          enum: [none, done, failed]
          default: none
        stop:
          description: >-
            Indicates whether traffic run has been successfully stopped.
          type: string
          enum: [none, done, failed]
          default: none
        pause:
          description: >-
            Indicates whether traffic run has been successfully paused.
          type: string
          enum: [none, done, failed]
          default: none
        resume:
          description: >-
            Indicates whether traffic run has been successfully resumed.
          type: string
          enum: [none, done, failed]
          default: none
        update:
          description: >-
            Indicates whether traffic config has been successfully updated.
          type: string
          enum: [none, done, failed]
          default: none
        o_connect:
          description: >-
            Indicates whether connection to intended traffic endpoints have been successfully established.
          type: string
          enum: [none, done, failed]
          default: none
        o_disconnect:
          description: >-
            Indicates whether intended traffic endpoints have been successfully disconnected.
          type: string
          enum: [none, done, failed]
          default: none
        o_update_layer1:
          description: >-
            Indicates whether layer1 configuration on intended traffic endpoints have been successfully updated.
          type: string
          enum: [none, done, failed]
          default: none
        o_start_transmit:
          description: >-
            Indicates whether flow transmit has been successfully started.
          type: string
          enum: [none, done, failed]
          default: none
        o_stop_transmit:
          description: >-
            Indicates whether flow transmit has been successfully stopped.
          type: string
          enum: [none, done, failed]
          default: none
        o_start_capture:
          description: >-
            Indicates whether port capture has been successfully started.
          type: string
          enum: [none, done, failed]
          default: none
        o_stop_capture:
          description: >-
            Indicates whether port capture has been successfully stopped.
          type: string
          enum: [none, done, failed]
          default: none
        o_clear_stats:
          description: >-
            Indicates whether Tx / Rx stats have been successfully cleared.
          type: string
          enum: [none, done, failed]
          default: none
        o_start_devices:
          description: >-
            Indicates whether intended emulated devices have been successfully started.
          type: string
          enum: [none, done, failed]
          default: none
        o_stop_devices:
          description: >-
            Indicates whether intended emulated devices have been successfully stopped.
          type: string
          enum: [none, done, failed]
          default: none
        errors:
          $ref: '../result/result.yaml#/components/schemas/Result.Errors'