openapi: 3.1.0

info:
  title: Control models
  description: >-
    All control schemas
  version: ^0.0.0

components:
  schemas:
    Link.State:
      description: >-
        Port link state.
      type: object
      required: [state]
      properties:
        port_names:
          description: >-
            The names of port objects to.
            An empty or null list will control all port objects.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Port/properties/name'
        state:
          description: >-
            The link state.
          type: string
          enum: [up, down]

    Transmit.State:
      description: >-
        Control the transmit state of flows.
      type: object
      required: [state]
      properties:
        flow_names:
          description: >-
            The names of flows to which the transmit state will be applied to.
            If the list of flow_names is empty or null the state will be applied
            to all configured flows.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Flow/properties/name'
        state:
          description: >-
            The transmit state.
          type: string
          enum: [start, stop, pause]

    Capture.State:
      description: >-
        Control port capture state
      type: object
      required: [state]
      properties:
        port_names:
          description: >-
            The name of ports to start capturing packets on.
            An empty or null list will control all port objects.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Port/properties/name'
        state:
          description: >-
            The capture state.
          type: string
          enum: [start, stop]

    Flows.Update:
      description: A container of flows with associated properties to be updated without affecting the transmit state
      type: object
      required: [property_names, flows]
      properties:
        property_names:
          description: Flow properties to be updated without affecting the transmit state
          type: array
          items: 
            type: string
            enum: [rate, size]
        flows:
          description: >-
            The list of configured flows for which given property will be updated.
          type: array
          items:
            $ref: '#/components/schemas/Flow'

    Route.State:
      description: >-
        Sets the device route state
      type: object
      required: [state]
      properties:
        names:
          description: >-
            The names of device route objects to control.
            If no names are specified then all route objects that match the
            x-constraint will be affected.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Bgp.V4RouteRange/properties/name'
          - '/components/schemas/Bgp.V6RouteRange/properties/name'
        state:
          description: >-
            Route specific states
          type: string
          enum: [withdraw, advertise]

    Ping.Request:
      description: >-
        Ping request details
      type: object
      properties:
        endpoints:
          description:
            Array of ping requests
          type: array
          items:
            $ref: './ping.yaml#/components/schemas/Ping'

    Protocol.State:
      description: >-
        Sets all configured protocols to `start` or `stop` state.
      type: object
      required: [state]
      properties:
        state:
          description: >-
            Protocol specific states
          type: string
          enum: [start, stop]