openapi: 3.1.0

info:
  title: Control models
  description: >-
    All control schemas
  version: ^0.0.0

components:
  schemas:
    Control.State:
      description: >-
        A container for the different types of states.
      type: object
      required: ['choice']
      properties:
        choice:
          type: string
          enum: [config_state, port_link_state, port_capture_state, flow_transmit_state]
        config_state:
          $ref: '#/components/schemas/Control.Config'
        port_link_state:
          $ref: '#/components/schemas/Control.PortLink'
        port_capture_state:
          $ref: '#/components/schemas/Control.PortCapture'
        flow_transmit_state:
          $ref: '#/components/schemas/Control.FlowTransmit'

    Control.Config:
      description: >-
        Control the configuration state on the traffic generator.
      type: object
      required: [config, state]
      properties:
        config:
          $ref: '../config/config.yaml#/components/schemas/Config'
        state:
          description: >-
            Set the configuration state on the traffic generator.
            - set is used to set the running configuration on the traffic generator.
            - set_start is used to set the running configuration and
            perform the neccessary operations needed to start transmit on all
            flows.
          type: string
          enum: [set, set_start]

    Control.PortLink:
      description: >-
        Control port link state
      type: object
      required: [state]
      properties:
        port_names:
          description: >-
            The names of port objects to.
            An empty or null list will control all port objects.
          type: array
          items:
            type: string
            x-constraint:
            - '/components/schemas/Port/properties/name'
        state:
          description: >-
            The link state.
          type: string
          enum: [up, down]

    Control.FlowTransmit:
      description: >-
        Control flow transmit state
      type: object
      required: [state]
      properties:
        flow_names:
          description: >-
            The names of flow objects to control.
            An empty or null list will control all flow objects.
          type: array
          items:
            type: string
            x-constraint:
            - '/components/schemas/Flow/properties/name'
        state:
          description: >-
            The transmit state.
          type: string
          enum: [start, stop, pause]

    Control.PortCapture:
      description: >-
        Control port capture state
      type: object
      required: [state]
      properties:
        port_names:
          description: >-
            The name of ports to start capturing packets on.
            An empty or null list will control all port objects.
          type: array
          items:
            type: string
            x-constraint:
            - '/components/schemas/Port/properties/name'
        state:
          description: >-
            The capture state.
          type: string
          enum: [start, stop]

