openapi: 3.0.3
info:
  title: Control models
  description: >-
    All control schemas
  version: ^0.0.0
components:
  schemas:
    Link.State:
      description: >-
        Port link state.
      type: object
      required: [state]
      properties:
        port_names:
          description: >-
            The names of port objects to.
            An empty or null list will control all port objects.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Port/properties/name'
          x-field-uid: 1
        state:
          description: >-
            The link state.
          type: string
          x-field-uid: 2
          x-enum:
            up:
              x-field-uid: 1
            down:
              x-field-uid: 2
    Transmit.State:
      description: >-
        Flow transmit state.
      type: object
      required: [state]
      properties:
        flow_names:
          description: >-
            The names of flows to which the transmit state will be applied to.
            If the list of flow_names is empty or null the state will be applied
            to all configured flows.

            If the list is not empty any flow that is not included in the list
            of flow_names MUST be ignored and not included in the state change.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Flow/properties/name'
          x-field-uid: 1
        state:
          description: >-
            The transmit state.

            If the value of the state property is 'start' then all flows
            defined by the 'flow_names' property will be started and the metric
            counters MUST be cleared prior to starting the flow(s).

            If the value of the state property is 'stop' then all flows
            defined by the 'flow_names' property will be stopped and the metric
            counters MUST NOT be cleared.

            If the value of the state property is 'pause' then all flows
            defined by the 'flow_names' property will be paused and the metric
            counters MUST NOT be cleared.

            If the value of the state property is 'resume' then any paused flows
            defined by the 'flow_names' property will start transmit at the
            point at which they were paused. Any flow that is stopped will
            start transmit at the beginning of the flow.
            The flow(s) MUST NOT have their metric counters cleared.
          type: string
          x-field-uid: 2
          x-enum:
            start:
              x-field-uid: 1
            stop:
              x-field-uid: 2
            pause:
              x-field-uid: 3
            resume:
              x-field-uid: 4
    Capture.State:
      description: >-
        Control port capture state
      type: object
      required: [state]
      properties:
        port_names:
          description: >-
            The names of ports to which the capture state will be applied to.
            If the list of port_names is empty or null the state will be applied
            to all configured ports.

            If the list is not empty any port that is not included in the list
            of port_names MUST be ignored and not included in the state change.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Port/properties/name'
          x-field-uid: 1
        state:
          description: >-
            The capture state.
          type: string
          x-field-uid: 2
          x-enum:
            start:
              x-field-uid: 1
            stop:
              x-field-uid: 2
    Flows.Update:
      description: >-
        A container of flows with associated properties to be updated without
        affecting the flows current transmit state.
      type: object
      required: [property_names, flows]
      properties:
        property_names:
          description: >-
            Flow properties to be updated without affecting the transmit state.
          type: array
          items:
            type: string
            x-enum:
              rate:
                x-field-uid: 1
              size:
                x-field-uid: 2
          x-field-uid: 1
        flows:
          description: >-
            The list of configured flows for which given property will be updated.
          type: array
          items:
            $ref: '#/components/schemas/Flow'
          x-field-uid: 2
    Route.State:
      description: >-
        Sets the device route state
      type: object
      required: [state]
      properties:
        names:
          description: >-
            The names of device route objects to control.
            If no names are specified then all route objects that match the
            x-constraint will be affected.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Bgp.V4RouteRange/properties/name'
          - '/components/schemas/Bgp.V6RouteRange/properties/name'
          - '/components/schemas/Isis.V4RouteRange/properties/name'
          - '/components/schemas/Isis.V6RouteRange/properties/name'
          x-field-uid: 1
        state:
          description: >-
            Route specific states
          type: string
          x-field-uid: 2
          x-enum:
            withdraw:
              x-field-uid: 1
            advertise:
              x-field-uid: 2
    Ping.Request:
      description: >-
        Ping request details
      type: object
      properties:
        endpoints:
          description: Array of ping requests
          type: array
          items:
            $ref: './ping.yaml#/components/schemas/Ping'
          x-field-uid: 1
    Protocol.State:
      description: >-
        Sets all configured protocols to `start` or `stop` state. Setting protocol state to `start` 
        shall be a no-op if preceding `set_config` API call was made with 
        `config.options.protocol_options.auto_start_all` set to `true` or if all the configured protocols are already started.
      type: object
      required: [state]
      properties:
        state:
          description: >-
            Protocol specific states
          type: string
          x-field-uid: 1
          x-enum:
            start:
              x-field-uid: 1
            stop:
              x-field-uid: 2
    Device.State:
      description: >-
        Sets attributes for the requested state/actions to be performed on device(s)
      type: object
      properties:
        choice:
          type: string
          x-field-uid: 1
          x-enum:
            lacp_member_state:
              x-field-uid: 1
        lacp_member_state:
          $ref: './lacp.yaml#/components/schemas/LacpMember.State'
          x-field-uid: 2
