openapi: 3.1.0

info:
  title: Control models
  description: >-
    All control schemas
  version: ^0.0.0

components:
  schemas:
    Control.State:
      type: object
      required: ['choice']
      properties:
        choice:
          type: string
          enum: [config, port_link, flow_transmit, port_capture]
        config:
          $ref: '#/components/schemas/Control.Config'
        port_link:
          $ref: '#/components/schemas/Control.PortLink'
        port_capture:
          $ref: '#/components/schemas/Control.PortCapture'
        flow_transmit:
          $ref: '#/components/schemas/Control.FlowTransmit'

    Control.Config:
      description: >-
        Control configuration state
      type: object
      properties:
        config:
          $ref: '../config/config.yaml#/components/schemas/Config'

    Control.PortLink:
      description: >-
        Control port link state
      type: object
      properties:
        port_names:
          description: >-
            The names of port objects to.
            An empty list will control all port objects.
          type: array
          items:
            type: string
            x-constraint:
            - '/components/schemas/Port/properties/name'
        state:
          description: >-
            The link state.
          type: string
          enum: [up, down]

    Control.FlowTransmit:
      description: >-
        Control flow transmit state
      type: object
      properties:
        flow_names:
          description: >-
            The names of flow objects to control.
            An empty list will control all flow objects.
          type: array
          items:
            type: string
            x-constraint:
            - '/components/schemas/Flow/properties/name'
        state:
          description: >-
            The transmit state.
          type: string
          enum: [start, stop, pause]

    Control.PortCapture:
      description: >-
        Control port capture state
      type: object
      properties:
        port_names:
          description: >-
            The name of a port to start capturing packets on.
            Allows for capture to be started on multiple ports.
          type: array
          items:
            type: string
            x-constraint:
            - '/components/schemas/Port/properties/name'

