openapi: 3.0.3
info:
  title: Control IPv4 models
  description: >-
    All control IPv4 schemas
  version: ^0.0.0
components:
  schemas:
    Action.Protocol.Ipv4:
      description: >-
        Actions associated with IPv4 on configured resources.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            ping:
              x-field-uid: 1
          x-field-uid: 1
        ping:
          $ref: "#/components/schemas/Action.Protocol.Ipv4.Ping"
          x-field-uid: 2
    Action.Response.Protocol.Ipv4:
      description: >-
        Response for actions associated with IPv4 on configured resources.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            ping:
              x-field-uid: 1
          x-field-uid: 1
        ping:
          $ref: "#/components/schemas/Action.Response.Protocol.Ipv4.Ping"
          x-field-uid: 2
    Action.Protocol.Ipv4.Ping:
      description: >-
        Request for initiating ping between multiple source and destination pairs.
      type: object
      properties:
        requests:
          description: >-
            List of IPv4 ping requests.
          type: array
          items:
            $ref: "#/components/schemas/Action.Protocol.Ipv4.PingRequest"
          x-field-uid: 1
    Action.Protocol.Ipv4.PingRequest:
      description: >-
        Request for initiating ping between a single source and destination pair.

        For ping request, 1 IPv4 ICMP Echo Request shall be sent and wait for ping response to
        either succeed or time out. The API wait timeout for each request shall be 300ms.
      type: object
      properties:
        src_name:
          description: >-
            Name of source IPv4 interface to be used.
          type: string
          x-constraint:
          - '/components/schemas/Device.Ipv4/properties/name'
          x-field-uid: 1
        dst_ip:
          description: >-
            Destination IPv4 address to ping.
          type: string
          format: ipv4
          x-field-uid: 2
    Action.Response.Protocol.Ipv4.Ping:
      description: >-
        Response for ping initiated between multiple source and destination pairs.
      type: object
      properties:
        responses:
          description: >-
            List of responses for IPv4 ping responses.
          type: array
          items:
            $ref: "#/components/schemas/Action.Response.Protocol.Ipv4.PingResponse"
          x-field-uid: 1
    Action.Response.Protocol.Ipv4.PingResponse:
      description: >-
        Response for ping initiated between a single source and destination pair.
      type: object
      required:
        - src_name
        - dst_ip
        - result
      properties:
        src_name:
          description: >-
            Name of source IPv4 interface used for ping.
          type: string
          x-constraint:
          - '/components/schemas/Device.Ipv4/properties/name'
          x-field-uid: 1
        dst_ip:
          description: >-
            Destination IPv4 address used for ping.
          type: string
          format: ipv4
          x-field-uid: 2
        result:
          description: >-
            Result of the ping request.
          type: string
          default: failed
          x-field-uid: 3
          x-enum:
            succeeded:
              x-field-uid: 1
            failed:
              x-field-uid: 2
