openapi: 3.0.3
info:
  title: IS-IS Control models
  description: >-
    All IS-IS control schemas
  version: ^0.0.0
components:
  schemas:
    Action.Protocol.Isis:
      description: >-
        Actions associated with IS-IS on configured resources.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            initiate_unplanned_restart:
              x-field-uid: 1
            initiate_starting:
              x-field-uid: 2
          x-field-uid: 1
        initiate_unplanned_restart:
          description: >-
            Initiates IS-IS Unplanned Graceful Restart process for the selected IS-IS routers.
            If no name is specified then Graceful Restart will be sent to all configured IS-IS routers.
            When an emulated IS-IS router is in the unplanned "Restarting" mode,
            it sends to the neighbor router (DUT) an IIH containing a Restart TLV with the RR (Restart Request) bit set.
            To emulate scenarios where a router sends Graceful Restart TlV this will result in 
            Unplanned Graceful Restart scenario to be triggered as per Reference: https://datatracker.ietf.org/doc/html/rfc5306.
          $ref: "#/components/schemas/Isis.Action.Protocol.Isis.StartParams"
          x-field-uid: 2
        initiate_start:
          description: >-
            Initiates IS-IS Start Process for the selected IS-IS routers. 
            It sends to the neighbor router (DUT) an IIH containing a Restart TLV with the SA (Suppress Adjacency Advertisement) bit set.
          $ref: "#/components/schemas/Isis.Action.Protocol.Isis.StartParams"
          x-field-uid: 3

    Isis.Action.Protocol.Isis.StartParams:
      description: >-
        Configuration for IS-IS Graceful Restart 
      type: object
      properties:
        router_names:
          description: >-
            The names of device objects to control.
          type: array
          items:
            type: string
          x-constraint:
          - /components/schemas/Device.IsisRouter/properties/name
          x-field-uid: 1
        restart_time:
          description: >-
            This is the estimated duration (in seconds) it will take for the
            IS-IS session to be re-established after a start/restart.
            This paramter is used in starting or restarting operation.
          type: integer
          format: uint32
          maximum: 4096
          default: 30
          minimum: 10
          x-field-uid: 2