openapi: 3.0.3
info:
  title: IS-IS Control models
  description: >-
    All IS-IS control schemas
  version: ^0.0.0
components:
  schemas:
    Action.Protocol.Isis:
      description: >-
        Actions associated with IS-IS on configured resources.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            initiate_starting_mode:
              x-field-uid: 1
            initiate_to_restarting_mode:
              x-field-uid: 2
          x-field-uid: 1
        initiate_starting_mode:
          $ref: "#/components/schemas/Action.Protocol.Isis.InitiateGracefulStart"
          x-field-uid: 2
        initiate_restarting_mode:
          $ref: "#/components/schemas/Action.Protocol.Isis.InitiateGracefulRestart"
          x-field-uid: 3

    Action.Protocol.Isis.InitiateGracefulStart:
      description: >-
        Initiates IS-IS Graceful Start process for the selected IS-IS routers.
        If no name is specified then Graceful Start will be sent to all configured IS-IS routers.
        To emulate scenarios where a router sends Graceful Restart TlV this will result in 
        Graceful tart scenario to be triggered as per Reference: https://datatracker.ietf.org/doc/html/rfc5306.
      type: object
      properties:
        router_names:
          description: >-
            The names of device rfc5306 objects to control.
          type: array
          items:
            type: string
          x-constraint:
          - /components/schemas/Device.IsisRouter/properties/name
          x-field-uid: 1

    Action.Protocol.Isis.InitiateGracefulRestart:
      description: >-
        Initiates IS-IS Graceful Restart process for the selected IS-IS routers.
        If no name is specified then Graceful Restart will be sent to all configured IS-IS routers.
        To emulate scenarios where a router sends Graceful Start TlV this will result in 
        Graceful Restart scenario to be triggered as perReference: https://datatracker.ietf.org/doc/html/rfc5306.
      type: object
      properties:
        router_names:
          description: >-
            The names of device rfc5306 objects to control.
          type: array
          items:
            type: string
          x-constraint:
          - /components/schemas/Device.IsisRouter/properties/name
          x-field-uid: 1