openapi: 3.0.3
info:
  title: IS-IS Control models
  description: >-
    All IS-IS control schemas
  version: ^0.0.0
components:
  schemas:
    Action.Protocol.Isis:
      description: >-
        Actions associated with IS-IS on configured resources.
      type: object
      properties:
        initiate_restart:
          description: >-
            Configuration for the initiation of the IS-IS Graceful Restart.
          $ref: "#/components/schemas/Isis.Action.Protocol.Isis.InitiateRestart"
          x-field-uid: 2

    Isis.Action.Protocol.Isis.InitiateRestart:
      description: |-
        Timers T1 and T2 are used both by a restarting router and a starting router. Timer T3 is used only by a restarting router.
        - Timer T1 is maintained per interface and indicates the time after which an unacknowledged (re)start attempt will be repeated. Its value is 3 seconds.
        - Timer T2 is maintained for each LSP database (LSDB) for Level 1 and Level 2. Default value is 90 seconds.
          When the timer T2 expires or is canceled, indicating that synchronization of that level is complete and SPF for that level is run.
        - Timer T3 is maintained for the entire system after which the router will declare that it has failed to achieve database synchronization 
          (by setting the overload bit in its own LSP). Its initial value is 65535 seconds and is set to minimum of the remaining times of received IIHs 
          containing a Restart TLV with the RA set.
      type: object
      properties:
        router_names:
          description: >-
            The names of device objects to control.
          type: array
          items:
            type: string
          x-constraint:
          - /components/schemas/Device.IsisRouter/properties/name
          x-field-uid: 1
        choice:
          type: string
          default: unplanned
          x-field-uid: 2
          x-enum:
            unplanned:
              x-field-uid: 1
        unplanned:
          $ref: "#/components/schemas/Isis.Action.Protocol.Isis.UnplannedRestart"
          x-field-uid: 3

    Isis.Action.Protocol.Isis.UnplannedRestart:
      description: >-
        Initiates IS-IS Unplanned Graceful Restart process for the selected IS-IS routers.
        If no name is specified then Graceful Restart will be sent to all configured IS-IS routers.
        When an emulated IS-IS router is in the unplanned "Restarting" mode,
        it sends an IIH PDU containing a Restart TLV with the RR (Restart Request) bit set and
        holding_time updated to as specified by user to indicate the maximum time within which this router 
        or routers will complete the graceful restart. 
        It waits for RA (Restart Acknowledge) in an IIH PDU from Neigbhor(s). 
        The timer T1 is maintained per interface and indicates the time after which an unacknowledged (re)start attempt will be repeated.
      type: object
      properties:
        holding_time:
          description: >-
            This is the estimated duration (in seconds) it will take for the
            IS-IS session to be re-established after a restart. The hold-timer in the IIH PDU is updated with this time.
          type: integer
          format: uint32
          maximum: 4096
          default: 30
          minimum: 1
          x-field-uid: 1
        restart_after:
          description: >-
            Once it receives Restarting TLV having RA bit set in a IIH PDU, 
            time (in seconds), after which IIH PDU, having Restart Tlv with RR bit unset, will be sent.
            This should result in IIH to be transmitted indicating restart is Completed, 
            not started i.e. RR bit is cleared and hold_timer is reset to normal.
          type: integer
          format: uint32
          maximum: 4096
          default: 10
          minimum: 1
          x-field-uid: 2