openapi: 3.1.0

info:
  title: LACP Control models
  description: >-
    All LACP control schemas
  version: ^0.0.0

components:
  schemas:
    LacpMember.State:
      description: >-
        Set LACP state for specified LAG Member Port(s).
      type: object
      required: [state]
      properties:
        port_names:
          description: >-
            The names of LAG member port objects to control.
            An empty or null list will control all LAG member port objects.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Lag.Port/properties/name'
        state:
          description: >-
            The LACP Member admin state.
            'up' will start transmission of LACPDUs on selected member ports.
            'down' will send a LACPDU with 'sync' flag unset and then stop transmission of LACPDUs on selected member ports.
          type: string
          enum: [up, down]
