openapi: 3.1.0

info:
  title: LACP State models
  description: >-
    All LACP State schemas
  version: ^0.0.0

components:
  schemas:
    Lacp.State:
      description: >-
        Set states specific to LACP
      type: object
      properties:
        choice:
          type: string
          enum: 
          - admin_state
        admin_state:
          $ref: '#/components/schemas/Lacp.Admin.State'
    Lacp.Admin.State:
      description: >-
        Set LACP admin state for specified LAG Member Port(s).
      type: object
      required: [state]
      properties:
        port_names:
          description: >-
            The names of LAG members (ports) for which the state has to be applied.
            An empty or null list will control all ports that are part of a LAG.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Port/properties/name'
        state:
          description: >-
            The LACP member admin state.
            'up' will start transmission of LACPDUs on selected member ports.
            'down' will send a LACPDU with 'sync' flag unset and then stop transmission of LACPDUs on selected member ports.
          type: string
          enum: [up, down]