openapi: 3.1.0

info:
  title: Control patch models
  description: >-
    All control patch schemas
  version: ^0.0.0

components:
  schemas:
    Control.Patch:
      description: >-
        Request for patching specific attributes of resources in traffic generator
      type: object
      properties:
        choice:
          type: string
          enum: 
          - flows
        flows:
          $ref: '#/components/schemas/Flows.Patch'
    Flows.Patch:
      description: >-
        A container of flows with associated properties to be updated without
        affecting their transmit state.
      type: object
      required: [property_names, flows]
      properties:
        property_names:
          description: >-
            Flow properties to be updated without affecting the transmit state.
          type: array
          items:
            type: string
            enum: [rate, size]
        flows:
          description: >-
            The list of configured flows for which given property will be updated.
          type: array
          items:
            $ref: '../flow/flow.yaml#/components/schemas/Flow'