openapi: 3.1.0
info:
  title: Ping models
  description: >-
    All ping schemas
  version: ^0.0.0
components:
  schemas:
    Ping:
      type: object
      properties:
        choice:
          description: IPv4 or IPv6 ping.
          type: string
          default: ipv4
          x-field-uid: 1
          x-enum:
            ipv4:
              x-field-uid: 1
            ipv6:
              x-field-uid: 2
        ipv4:
          $ref: '#/components/schemas/Ping.Ipv4'
          x-field-uid: 2
        ipv6:
          $ref: '#/components/schemas/Ping.Ipv6'
          x-field-uid: 3
    Ping.Ipv4:
      type: object
      properties:
        src_name:
          description: >-
            A base IPv4 interface
          type: string
          x-constraint:
          - '/components/schemas/Device.Ipv4Base/properties/name'
          x-field-uid: 1
        dst_ip:
          description: >-
            IPv4 address to ping
          type: string
          format: ipv4
          x-field-uid: 2
    Ping.Ipv6:
      type: object
      properties:
        src_name:
          description: >-
            A base IPv6 interface
          type: string
          x-constraint:
          - '/components/schemas/Device.Ipv6Base/properties/name'
          x-field-uid: 1
        dst_ip:
          description: >-
            IPv6 addresses to ping.
          type: string
          format: ipv6
          x-field-uid: 2
    Ping.Response:
      description: >-
        A container for ping responses.
      type: object
      properties:
        responses:
          type: array
          items:
            $ref: '#/components/schemas/Response'
          x-field-uid: 1
    Response:
      type: object
      properties:
        src_name:
          description: >-
            The name of the source IPv4 or IPv6 interface from which ping was sent.
          type: string
          x-constraint:
          - '/components/schemas/Device.Ipv4Base/properties/name'
          - '/components/schemas/Device.Ipv6Base/properties/name'
          x-field-uid: 1
        dst_ip:
          description: >-
            Destination address.
          type: string
          x-field-uid: 2
        result:
          description: >-
            Result of the ping request.
          type: string
          default: failure
          x-field-uid: 3
          x-enum:
            success:
              x-field-uid: 1
            failure:
              x-field-uid: 2
