openapi: 3.0.3
info:
  title: Control protocol models
  description: >-
    All control protocol schemas
  version: ^0.0.0
components:
  schemas:
    State.Protocol.All:
      description: >-
        Sets all configured protocols to `start` or `stop` state.
        
        Setting protocol state to `start` shall be a no-op if preceding `set_config` API call
        was made with `config.options.protocol_options.auto_start_all` set to `true` or if
        all the configured protocols are already started.
      type: object
      required:
        - state
      properties:
        state:
          description: >-
            Protocol states
          type: string
          x-field-uid: 1
          x-enum:
            start:
              x-field-uid: 1
            stop:
              x-field-uid: 2
    State.Protocol.Route:
      description: >-
        Sets the state of configured routes
      type: object
      required:
        - state
      properties:
        names:
          description: >-
            The names of device route objects to control.
            If no names are specified then all route objects that match the
            x-constraint will be affected.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Bgp.V4RouteRange/properties/name'
          - '/components/schemas/Bgp.V4RouteRange/properties/group'
          - '/components/schemas/Bgp.V6RouteRange/properties/name'
          - '/components/schemas/Bgp.V6RouteRange/properties/group'
          - '/components/schemas/Isis.V4RouteRange/properties/name'
          - '/components/schemas/Isis.V6RouteRange/properties/name'
          x-field-uid: 1
        state:
          description: >-
            Route states
          type: string
          x-field-uid: 2
          x-enum:
            withdraw:
              x-field-uid: 1
            advertise:
              x-field-uid: 2
    State.Protocol.Lacp:
      description: >-
        Sets state of configured LACP
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            admin:
              x-field-uid: 1
          x-field-uid: 1
        admin:
          $ref: '#/components/schemas/State.Protocol.Lacp.Admin'
          x-field-uid: 2
    State.Protocol.Lacp.Admin:
      description: >-
        Sets admin state of LACP configured on LAG members
      properties:
        lag_member_names:
          description: >-
            The names of LAG members (ports) for which the state has to be applied.
            An empty or null list will control all LAG members.
          type: array
          items:
            type: string
          x-constraint:
          - '/components/schemas/Port/properties/name'
          x-field-uid: 1
        state:
          description: >-
            The LACP Member admin state.
            'up' will send LACPDUs with 'sync' flag set on selected member ports.
            'down' will send LACPDUs with 'sync' flag unset on selected member ports.
          type: string
          x-field-uid: 2
          x-enum:
            up:
              x-field-uid: 1
            down:
              x-field-uid: 2