openapi: 3.0.3
info:
  title: Control state models
  description: >-
    All control state schemas
  version: ^0.0.0
components:
  schemas:
    Control.State:
      description: >-
        Request for setting operational state of configured resources.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            port:
              x-field-uid: 1
            protocol:
              x-field-uid: 2
            traffic:
              x-field-uid: 3
          x-field-uid: 1
        port:
          $ref: '#/components/schemas/State.Port'
          x-field-uid: 2
        protocol:
          $ref: '#/components/schemas/State.Protocol'
          x-field-uid: 3
        traffic:
          $ref: '#/components/schemas/State.Traffic'
          x-field-uid: 4
    State.Port:
      description: >-
        States associated with configured ports.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            link:
              x-field-uid: 1
            capture:
              x-field-uid: 2
          x-field-uid: 1
        link:
          $ref: './port.yaml#/components/schemas/State.Port.Link'
          x-field-uid: 2
        capture:
          $ref: './port.yaml#/components/schemas/State.Port.Capture'
          x-field-uid: 3
    State.Traffic:
      description: >-
        States associated with configured flows
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            flow_transmit:
              x-field-uid: 1
          x-field-uid: 1
        flow_transmit:
          $ref: './traffic.yaml#/components/schemas/State.Traffic.FlowTransmit'
          x-field-uid: 2
    State.Protocol:
      description: >-
        States associated with protocols on configured resources.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            all:
              x-field-uid: 1
            route:
              x-field-uid: 2
            lacp:
              x-field-uid: 3
            bgp:
              x-field-uid: 4
            isis:
              x-field-uid: 5
            ospfv2:
              x-field-uid: 6
          x-field-uid: 1
        all:
          $ref: './protocol.yaml#/components/schemas/State.Protocol.All'
          x-field-uid: 2
        route:
          $ref: './protocol.yaml#/components/schemas/State.Protocol.Route'
          x-field-uid: 3
        lacp:
          $ref: './protocol.yaml#/components/schemas/State.Protocol.Lacp'
          x-field-uid: 4
        bgp:
          $ref: './protocol.yaml#/components/schemas/State.Protocol.Bgp'
          x-field-uid: 5
        isis:
          $ref: './protocol.yaml#/components/schemas/State.Protocol.Isis'
          x-field-uid: 6
        ospfv2:
          $ref: './protocol.yaml#/components/schemas/State.Protocol.Ospfv2'
          x-field-uid: 7
        rocev2:
          $ref: './protocol.yaml#/components/schemas/State.Protocol.Rocev2'
          x-field-uid: 8