components:
  schemas:
    PANGPSettings:
      properties:
        authsettings:
          x-field-uid: 11
          x-include: ../tunnelsettings/tunnelsettings.yaml#/components/schemas/TunnelSettings/properties/authsettings
        espproberetrytimeout:
          default: 60
          format: int32
          type: integer
          x-field-uid: 1
        espprobetimeout:
          default: 65
          format: int32
          type: integer
          x-field-uid: 2
        gpclientversion:
          default: 5.1.5-8
          description: GP Client Version
          type: string
          x-field-uid: 3
        isportal:
          default: true
          description: 'A flag indicating if the tunnel is connected to PAN Portal
            instead of a direct connection to the PAN GP VPN Gateway (default: true).'
          type: boolean
          x-field-uid: 4
        links:
          items:
            $ref: ../apilink/apilink.yaml#/components/schemas/APILink
          type: array
          x-field-uid: 10
        outertcpprofile:
          x-field-uid: 12
          x-include: ../tunnelsettings/tunnelsettings.yaml#/components/schemas/TunnelSettings/properties/outertcpprofile
        outertlsclientprofile:
          $ref: ../tlsprofile/tlsprofile.yaml#/components/schemas/TLSProfile
          default: method(GetDefaultClientTlsProfilePangpSettings)
          x-field-uid: 5
        pangpencapsulation:
          $ref: ../pangpencapsulation/pangpencapsulation.yaml#/components/schemas/PANGPEncapsulation
          x-field-uid: 6
        portalhostname:
          pattern: (^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)|^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)+([A-Za-z]|[A-Za-z][A-Za-z0-9\-]*[A-Za-z0-9]))|(^$)|^((((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))|(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|(([0-9a-fA-F]{1,4}:){5,5}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}|([0-9a-fA-F]{1,4}:){1,4}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){2,2}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){3,3}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){4,4})|:(:[0-9a-fA-F]{1,4}){1,5}):((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))))$
          type: string
          x-field-uid: 7
        vpngateway:
          type: string
          x-field-uid: 8
        vpngateways:
          items:
            type: string
          type: array
          x-field-uid: 9
      required:
      - vpngateways
      - portalhostname
      type: object
