openapi: 3.1.0

info:
  title: Port models
  version: ^0.0.0

components:
  schemas:
    Port:
      description: >-
        An abstract test port.
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        location:
          description: >- 
            The location of a test port. 
            It is the endpoint where packets will emit from.

            Test port locations can be the following:
              - physical appliance with multiple ports
              - physical chassis with multiple cards and ports
              - local interface
              - virtual machine, docker container, kubernetes cluster

            The test port location format is implementation specific.
            Use the /results/capabilities API to determine what formats an 
            implementation supports for the location property.

            Get the configured location state by using the /results/port API.
          type: string
        devices:
          type: array
          items:
            $ref: '../device/device.yaml#/components/schemas/Device'
        capture:
          $ref: '#/components/schemas/Port.Capture'

    Port.Capture:
      description: >-
        Container for capture filter information.
      type: object
      required: [choice]
      properties:
        choice: 
          description: >-
            The type of filter.
          type: string
          enum: [basic, pcap]
        basic:
          description: >-
            An array of basic filters.
            The filters supported are source address, destination address and
            custom.  
          type: array
          items:
            $ref: '#/components/schemas/Port.BasicFilter'
        pcap:
          description: >-
            The content of this property must be of pcap filter syntax.
            https://www.tcpdump.org/manpages/pcap-filter.7.html
          type: string
        overwrite:
          description: >-
            Overwrite the capture buffer.
          type: boolean
          default: false
        format:
          description: >-
            The format of the capture file.
          type: string
          enum: [pcap, pcapng]
          default: pcap

    Port.BasicFilter:
      description: >-
        A container for different types of basic capture filters.
      type: object
      required: [choice]
      properties:
        choice:
          type: string
          enum: [mac_address, custom]
        mac_address:
          $ref: '#/components/schemas/Port.MacAddressFilter'
        custom:
          $ref: '#/components/schemas/Port.CustomFilter'
        and_operator:
          type: boolean
          default: true
        not_operator:
          type: boolean
          default: false

    Port.MacAddressFilter:
      description: >-
        A container for a mac address capture filter.
      type: object
      required: [mac, filter]
      properties:
        mac:
          description: >-
            The type of mac address filters.
            This can be either source or destination.
          type: string
          enum: [source, destination]
        filter:
          description: >-
            The value of the mac address.
          type: string
        mask:
          description: >-
            The value of the mask to be applied to the mac address.
          type: string

    Port.CustomFilter:
      description: >-
        A container for a custom capture filter.
      type: object
      required: [filter, offset]
      properties:
        filter:
          description: >-
            The value to filter on.
          type: string
        mask:
          description: >-
            The mask to be applied to the filter.
          type: string
        offset:
          description: >-
            The offset in the packet to filter at.
          type: integer

    Port.Options:
      description: >-
        Common port options that apply to all configured Port.Port objects. 
      type: object
      properties:
        location_preemption:
          description: >-
            Preempt all the test port locations as defined by the 
            Port.Port.properties.location.
            If the test ports as defined by their location values are in use and 
            this value is true, the test ports will be preempted.
          type: boolean
          default: false

 