openapi: 3.0.3
info:
  title: Port models
  version: ^0.0.0
components:
  schemas:
    Port:
      description: >-
        An abstract test port.
      type: object
      properties:
        location:
          description: >-
            The location of a test port.  It is the endpoint where packets will emit
            from.

            Test port locations can be the following:
              - physical appliance with multiple ports
              - physical chassis with multiple cards and ports
              - local interface
              - virtual machine, docker container, kubernetes cluster

            The test port location format is implementation specific.
            Use the /results/capabilities API to determine what formats an  implementation
            supports for the location property.

            Get the configured location state by using the /results/port API.
          type: string
          x-field-uid: 1
        name:
          x-include: ../common/common.yaml#/components/schemas/Named.Object/properties/name
          x-field-uid: 2
      required: [name]
    Port.Options:
      description: >-
        Common port options that apply to all configured Port objects. 
      type: object
      properties:
        location_preemption:
          description: >-
            Preempt all the test port locations as defined by the  Port.Port.properties.location.
            If the test ports defined by their location values are in use and  this
            value is true, the test ports will be preempted.
          type: boolean
          default: false
          x-field-uid: 1
        data_integrity:
          description: >-
            Check and validate that flow payload has not been modified when received on Rx port.
            It applies to all flows across all ports and if set to true, it is reported in data
            integrity in port statistics with frame count both for frames with unmodified payload as
            frames_rx and for frames which has payload modified during transit as errors.
          type: boolean
          default: false
          x-field-uid: 2
        frame_ordering:
          description: >-
            Frame ordering is done when data is transmitted as a sequence of frames in a network
            comprising multiple terminal stations. Each terminal has a provision for arranging the
            received messages in the order of reception of frames. Within each frame, the received
            messages are arranged in a predetermined order of frames received.
          type: string
          default: no_ordering
          x-enum:
            no_ordering:
              description: >-
                If you select this option, no specific ordering is followed when packets are transmitted.
              x-field-uid: 1
            rfc2889:
              description: >-
                If you select this option, the frame ordering is done by RFC2889. Stream ordering can
                be used for assigning interleaved traffic streams between transmitting and receiving
                ports, when creating and applying the streams. This process is used to prevent a
                receiving (destination) port from being overloaded by simultaneous streams from
                multiple transmitting (source) ports. The basis of the stream ordering is the set of
                procedures defined in RFC 2889, "Benchmarking Methodology for LAN Switching Devices,"
                which uses a round-robin sequencing for transmitting frames. Stream ordering is done
                before the streams are sent to the source ports for transmission.
              x-field-uid: 2
          x-field-uid: 3
