openapi: 3.0.3
info:
  title: Fragments
  version: ^0.0.0
  description: >-
    This file should be used as a repository for fragments that will be used
    as a direct inline replacement where ever the keyword is found
components:
  schemas:
    Named.Object:
      type: object
      required: [name]
      properties:
        name:
          description: >-
            Globally unique name of an object.
            It also serves as the primary key for arrays of objects.
          type: string
          x-field-uid: 1
          x-unique: global
    ChoiceNone:
      description: >-
        A empty container that is used to indicate a null choice.
      type: object
