openapi: 3.0.3
info:
  title: Fragments
  version: ^0.0.0
  description: >-
    This file should be used as a repository for fragments that will be used
    as a direct inline replacement where ever the keyword is found
components:
  schemas:
    Named.Object:
      type: object
      required: [name]
      properties:
        name:
          description: >-
            Globally unique name of an object.
            It also serves as the primary key for arrays of objects.
          type: string
          # Disallow leading and trailing whitespace
          pattern: '^\S(.*\S)?$'
          x-field-uid: 1
          x-unique: global

    Described.Object:
      description: >-
        An object that can be described with a textual description.
      type: object
      properties:
        description:
          type: string
          description: >-
            A detailed description of the object.
          x-field-uid: 1

    Identified.Object:
      description: >-
        An object that can be described with a string UUID.
      type: object
      properties:
        id:
          type: string
          description: >-
            The unique ID of an object.
          x-field-uid: 1

    Placeholder.Object:
      description: >-
        A placeholder object for fields that are yet to be properly defined.
      type: object
      properties:
        value:
          type: string
          description: >-
            Placeholder type for fields that are yet to be defined.
          x-field-uid: 1

    Tagged.Object:
      description: >-
        An object that can be associated with a list of tags.
      type: object
      properties:
        tags:
          type: array
          items:
            type: string
          uniqueItems: true
          default: []
          description: >-
            List of tags associated with this object.
          x-field-uid: 1

    Versioned.Object:
      description: >
        An object that has a version.
      type: object
      properties:
        version:
          type: string
          format: semantic-version
          description: >-
            Semver (semantic versioning) formatted version of containing object.
          x-field-uid: 1

    StringMap:
      description: >-
        A map of string keys to string values.
      type: object
      additionalProperties:
        type: string
