openapi: 3.1.0

info:
  title: Ethernet Pause packet header model
  version: ^0.0.0

components:
  schemas:
    Flow.EthernetPause:
      description: >-
        IEEE 802.3x Ethernet Pause packet header.
        - dst: 01:80:C2:00:00:01 48bits
        - src: 48bits 
        - ether_type: 0x8808 16bits
        - control_op_code: 0x0001 16bits
        - time: 0x0000 16bits
      type: object
      properties:
        dst:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        src:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ether_type:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        control_op_code:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        time:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
