openapi: 3.1.0

info:
  title: Gre traffic packet header
  version: ^0.0.0

components:
  schemas:
    Flow.Gre:
      description: Gre packet header
      type: object
      properties:
        checksum_present:
          description: >-
            Checksum bit.
            Set to 1 if a checksum is present.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        key_present:
          description: >-
            Key bit.
            Set to 1 if a key is present.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        seq_number_present:
          description: >-
            Sequence number bit.
            Set to 1 if a sequence number is present.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        reserved0:
          description: >-
            Reserved bits.
            Set to 0.
            9 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        version:
          description: >-
            Gre version number.
            Set to 0.
            3 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        protocol:
          description: >-
            Indicates the ether protocol type of the encapsulated payload.
            - 0x0800 ipv4
            - 0x86DD ipv6
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        checksum:
          description: >-
            Present if the checksum_present bit is set.
            Contains the checksum for the gre header and payload.
            16 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        reserved1:
          description: >-
            Reserved bits.
            Set to 0.
            16 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        key:
          description: >-
            Present if the key_present bit is set.
            Contains an application specific key value.
            32 bits
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        sequence_number:
          description: >-
            Present if the seq_number_present bit is set.
            Contains a sequence number for the gre packet.
            32 bits
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
