openapi: 3.1.0

info:
  title: GTP version 1 packet header models
  version: ^0.0.0

components:
  schemas:
    Flow.Gtpv1:
      description: GTPv1 packet header
      type: object
      properties:
        version:
          description: >-
            It is a 3-bit field. For GTPv1, this has a value of 1.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        protocol_type:
          description: >-
            A 1-bit value that differentiates GTP (value 1) from GTP' (value 0).
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        reserved:
          description: >-
            A 1-bit reserved field (must be 0).
          $ref: '#/components/schemas/Flow.Ipv4.Priority'
        e_flag:
          description: >-
            A 1-bit value that states whether there is an extension header optional field.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        s_flag:
          description: >-
            A 1-bit value that states whether there is a Sequence Number optional field.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        pn_flag:
          description: >-
            A 1-bit value that states whether there is a N-PDU number optional field.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        message_type:
          description: >-
            An 8-bit field that indicates the type of GTP message. 
            Different types of messages are defined in 3GPP TS 29.060 section 7.1
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        message_length:
          description: >-
            A 16-bit field that indicates the length of the payload in bytes (rest of the packet following the mandatory 8-byte GTP header). 
            Includes the optional fields.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        teid:
          description: >-
            Tunnel endpoint identifier.
            A 32-bit(4-octet) field used to multiplex different connections in the same GTP tunnel.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        squence_number:
          description: >-
            An (optional) 16-bit field. 
            This field exists if any of the e_flag, s_flag, or pn_flag bits are on. 
            The field must be interpreted only if the s_flag bit is on.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        n_pdu_number:
          description: >-
            An (optional) 8-bit field. 
            This field exists if any of the e_flag, s_flag, or pn_flag bits are on. 
            The field must be interpreted only if the pn_flag bit is on.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        next_extension_header_type:
          description: >-
            An (optional) 8-bit field. 
            This field exists if any of the e_flag, s_flag, or pn_flag bits are on. 
            The field must be interpreted only if the e_flag bit is on.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        extension_headers:
          description: >-
            A list of optional extension headers.
          type: array
          items:
            $ref: '#/components/schemas/Flow.GtpExtension'
    
    Flow.GtpExtension:
      type: object
      properties:
        extension_length:
          description: >-
            An 8-bit field. 
            This field states the length of this extension header, including the length, the contents, and the next extension header field, in 4-octet units, so the length of the extension must always be a multiple of 4.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        contents:
          description: >-
            The extension header contents.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        next_extension_header:
          description: >-
            An 8-bit field. 
            It states the type of the next extension, or 0 if no next extension exists. 
            This permits chaining several next extension headers.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
