openapi: 3.1.0

info:
  title: GTP version 2 packet header models
  version: ^0.0.0

components:
  schemas:
    Flow.Gtpv2:
      description: GTPv2 packet header
      type: object
      properties:
        version:
          description: >-
            It is a 3-bit field. For GTPv2, this has a value of 2.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        piggybacking_flag:
          description: >-
           If this bit is set to 1 then another GTP-C message with its own header shall be present at the end of the current message.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        teid_flag:
          description: >-
            If this bit is set to 1 then the TEID field will be present between the message length and the sequence number.
            All messages except Echo and Echo reply require TEID to be present.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        spare1:
          description: >-
            A 3-bit reserved field (must be 0).
          $ref: '#/components/schemas/Flow.Pattern'
        message_type:
          description: >-
            An 8-bit field that indicates the type of GTP message.
            Different types of messages are defined in 3GPP TS 29.060 section 7.1
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        message_length:
          description: >-
            A 16-bit field that indicates the length of the payload in bytes (excluding the mandatory GTP-c header (first 4 bytes).
            Includes the TEID and sequence_number if they are present.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        teid:
          description: >-
            Tunnel endpoint identifier.
            A 32-bit (4-octet) field used to multiplex different connections in the same GTP tunnel.
            Is present only if the teid_flag is set.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        sequence_number:
          description: >-
            A 24-bit field.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        spare2:
          description: >-
            An 8-bit reserved field (must be 0).
          $ref: '#/components/schemas/Flow.Pattern'
