openapi: 3.1.0

info:
  title: Packet header model
  version: ^0.0.0

components:
  schemas:
    Flow.Header:
      description: >-
        Container for all traffic packet headers
      type: object
      required: [choice]
      properties:
        choice:
          type: string
          enum: [custom, ethernet, vlan, vxlan, ipv4, ipv6, pfcpause, ethernetpause, tcp, udp, gre, gtpv1, gtpv2, arp, ppp, igmpv1]
        custom:
          $ref: './custom.yaml#/components/schemas/Flow.Custom'
        ethernet:
          $ref: './ethernet.yaml#/components/schemas/Flow.Ethernet'
        vlan:
          $ref: './vlan.yaml#/components/schemas/Flow.Vlan'
        vxlan:
          $ref: './vxlan.yaml#/components/schemas/Flow.Vxlan'
        ipv4:
          $ref: './ipv4.yaml#/components/schemas/Flow.Ipv4'
        ipv6:
          $ref: './ipv6.yaml#/components/schemas/Flow.Ipv6'
        pfcpause:
          $ref: './pfcpause.yaml#/components/schemas/Flow.PfcPause'
        ethernetpause:
          $ref: './ethernetpause.yaml#/components/schemas/Flow.EthernetPause'
        tcp:
          $ref: './tcp.yaml#/components/schemas/Flow.Tcp'
        udp:
          $ref: './udp.yaml#/components/schemas/Flow.Udp'
        gre:
          $ref: './gre.yaml#/components/schemas/Flow.Gre'
        gtpv1:
          $ref: './gtp.yaml#/components/schemas/Flow.Gtpv1'
        gtpv2:
          $ref: './gtpv2.yaml#/components/schemas/Flow.Gtpv2'
        arp:
          $ref: './arp.yaml#/components/schemas/Flow.Arp'
        ppp:
          $ref: './ppp.yaml#/components/schemas/Flow.Ppp'
        igmpv1:
          $ref: './igmpv1.yaml#/components/schemas/Flow.Igmpv1'

