openapi: 3.1.0

info:
  title: IGMPv1 traffic packet header
  version: ^0.0.0

components:
  schemas:
    Flow.Igmpv1:
      description: IGMPv1 packet header
      type: object
      properties:
        version:
          description: >-
            IGMP version field.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        type:
          description: >-
            Type of IGMP message, either a Host Membership Query or a Host Membership Report
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        unused:
          description: >-
            Unused field in IGMPv1
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        checksum:
          description: >-
            Checksum of the IGMP message
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        group_address:
          description: >-
            Group Address field
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'