openapi: 3.1.0

info:
  title: Ipv4 packet header model
  version: ^0.0.0

components:
  schemas:
    Flow.Ipv4:
      description: IPv4 packet header
      type: object
      properties:
        version:
          x-pattern:
            description: >-
              Version
            format: integer
            length: 4
            default: 4
            features: [count, metric_group]
        header_length:
          x-pattern:
            description: >-
              Header length
            format: integer
            length: 4
            default: 5
            features: [auto, count, metric_group]
        priority:
          $ref: '#/components/schemas/Flow.Ipv4.Priority'
        total_length:
          x-pattern:
            description: >-
              Version
            format: integer
            length: 16
            default: 120
            features: [auto, count, metric_group]
        identification:
          x-pattern:
            description: >-
              Identification
            format: integer
            length: 16
            default: 0
            features: [count, metric_group]
        reserved:
          x-pattern:
            description: >-
              Version
            format: integer
            length: 1
            default: 0
            features: [count, metric_group]
        dont_fragment:
          x-pattern:
            description: >-
              Dont fragment
            format: integer
            length: 1
            default: 0
            features: [count, metric_group]
        more_fragments:
          x-pattern:
            description: >-
              More fragments
            format: integer
            length: 1
            default: 0
            features: [count, metric_group]
        fragment_offset:
          x-pattern:
            description: >-
              Fragment offset
            format: integer
            length: 5
            default: 0
            features: [count, metric_group]
        time_to_live:
          x-pattern:
            description: >-
              Time to live
            format: integer
            length: 8
            default: 64
            features: [count, metric_group]
        protocol:
          x-pattern:
            description: >-
              Protocol, default is 61 any host internal protocol
            format: integer
            length: 8
            default: 61
            features: [count, metric_group]
        header_checksum:
          x-pattern:
            description: >-
              Header checksum
            format: checksum
            length: 16
        src:
          x-pattern:
            description: >-
              Source address
            format: ipv4
            default: 0.0.0.0
            features: [count, metric_group]
        dst:
          x-pattern:
            description: >-
              Destination address
            format: ipv4
            default: 0.0.0.0
            features: [count, metric_group]

    Flow.Ipv4.Priority:
      description: >-
        A container for ipv4 raw, tos, dscp ip priorities.
      type: object
      x-constants:
        PRIORITY_RAW: 0
      required: [choice]
      properties:
        choice:
          type: string
          enum: [raw, tos, dscp]
        raw: 
          x-pattern:
            description: >-
              Raw priority
            format: hex
            length: 8
            default: '00'
            features: [count, metric_group]
        tos: 
          $ref: '#/components/schemas/Flow.Ipv4.Tos'
        dscp:
          $ref: '#/components/schemas/Flow.Ipv4.Dscp'

    Flow.Ipv4.Dscp:
      description: >-
        Differentiated services code point (DSCP) packet field.
      type: object
      x-constants:
        phb_default: 0
        phb_cs1: 8
        phb_cs2: 16
        phb_cs3: 24
        phb_cs4: 32
        phb_cs5: 40
        phb_cs6: 48
        phb_cs7: 56
        phb_af11: 10
        phb_af12: 12
        phb_af13: 14
        phb_af21: 18
        phb_af22: 20
        phb_af23: 22
        phb_af31: 26
        phb_af32: 28
        phb_af33: 30
        phb_af41: 34
        phb_af42: 36
        phb_af43: 38
        phb_ef46: 46
        ecn_non_capable: 0
        ecn_capable_transport_0: 1
        ecn_capable_transport_1: 2
        ecn_congestion_encountered: 3
      properties:
        phb: 
          x-pattern:
            description: >-
              Per hop behavior
            format: integer
            length: 6
            default: 0
            features: [count, metric_group]
        ecn: 
          x-pattern:
            description: >-
              Explicit congestion notification
            format: integer
            length: 2
            default: 0
            features: [count, metric_group]

    Flow.Ipv4.Tos:
      description: >-
        Type of service (TOS) packet field.
      type: object
      x-constants:
        pre_routine: 0
        pre_priority: 1
        pre_immediate: 2
        pre_flash: 3
        pre_flash_override: 4
        pre_critic_ecp: 5
        pre_internetwork_control: 6
        pre_network_control: 7
        normal: 0
        low: 1
      properties:
        precedence: 
          x-pattern:
            description: >-
              Precedence
            format: integer
            length: 3
            default: 0
            features: [count, metric_group]
        delay: 
          x-pattern:
            description: >-
              Delay
            format: integer
            length: 1
            default: 0
            features: [count, metric_group]
        throughput: 
          x-pattern:
            description: >-
              Throughput
            format: integer
            length: 1
            default: 0
            features: [count, metric_group]
        reliability: 
          x-pattern:
            description: >-
              Reliability
            format: integer
            length: 1
            default: 0
            features: [count, metric_group]
        monetary: 
          x-pattern:
            description: >-
              Monetary
            format: integer
            length: 1
            default: 0
            features: [count, metric_group]
        unused: 
          x-pattern:
            description: >-
              Unused
            format: integer
            length: 1
            default: 0
            features: [count, metric_group]
