openapi: 3.1.0

info:
  title: Ipv4 packet header model
  version: ^0.0.0

components:
  schemas:
    Flow.Ipv4:
      description: Ipv4 packet header
      type: object
      properties:
        version:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        header_length:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        priority:
          $ref: '#/components/schemas/Flow.Ipv4.Priority'
        total_length:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        identification:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        reserved:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        dont_fragment:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        more_fragments:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        fragment_offset:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        time_to_live:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        protocol:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        header_checksum:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        src:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        dst:
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'

    Flow.Ipv4.Priority:
      description: >-
        A container for ipv4 raw, tos, dscp ip priorities.
      type: object
      x-constants:
        PRIORITY_RAW: 0
      required: [choice]
      properties:
        choice:
          type: string
          enum: [raw, tos, dscp]
        raw: 
          description: >-
            Raw priority is 8 bits: >=0 raw <=255
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        tos: 
          $ref: '#/components/schemas/Flow.Ipv4.Tos'
        dscp:
          $ref: '#/components/schemas/Flow.Ipv4.Dscp'

    Flow.Ipv4.Dscp:
      description: >-
        Differentiated services code point (DSCP) packet field.
      type: object
      x-constants:
        phb_default: 0
        phb_cs1: 8
        phb_cs2: 16
        phb_cs3: 24
        phb_cs4: 32
        phb_cs5: 40
        phb_cs6: 48
        phb_cs7: 56
        phb_af11: 10
        phb_af12: 12
        phb_af13: 14
        phb_af21: 18
        phb_af22: 20
        phb_af23: 22
        phb_af31: 26
        phb_af32: 28
        phb_af33: 30
        phb_af41: 34
        phb_af42: 36
        phb_af43: 38
        phb_ef46: 46
        ecn_non_capable: 0
        ecn_capable_transport_0: 1
        ecn_capable_transport_1: 2
        ecn_congestion_encountered: 3
      properties:
        phb: 
          description: >-
            phb (per-hop-behavior) value is 6 bits: >=0 PHB <=63.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        ecn: 
          description: >-
            ecn (explicit-congestion-notification) value is 2 bits: >=0 ecn <=3
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'

    Flow.Ipv4.Tos:
      description: >-
        Type of service (TOS) packet field.
      type: object
      x-constants:
        pre_routine: 0
        pre_priority: 1
        pre_immediate: 2
        pre_flash: 3
        pre_flash_override: 4
        pre_critic_ecp: 5
        pre_internetwork_control: 6
        pre_network_control: 7
        normal: 0
        low: 1
      properties:
        precedence: 
          description: >-
            Precedence value is 3 bits: >=0 precedence <=3
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        delay: 
          description: >-
            Delay value is 1 bit: >=0 delay <=1
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        throughput: 
          description: >-
            Throughput value is 1 bit: >=0 throughput <=3
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        reliability: 
          description: >-
            Reliability value is 1 bit: >=0 reliability <=1
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        monetary: 
          description: >-
            Monetary value is 1 bit: >=0 monetary <=1
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        unused: 
          description: >-
            Unused value is 1 bit: >=0 unused <=1
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
