openapi: 3.1.0

info:
  title: Ipv6 traffic packet header
  version: ^0.0.0

components:
  schemas:
    Flow.Ipv6:
      description: Ipv6 packet header
      type: object
      properties:
        version:
          description: >-
            Default version number is 6 (bit sequence 0110)
            4 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        traffic_class:
          description: >-
            8 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        flow_label:
          description: >-
            20 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        payload_length:
          description: >-
            16 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        next_header:
          description: >-
            8 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        hop_limit:
          description: >-
            8 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        src:
          description: >-
            128 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        dst:
          description: >-
            128 bits
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
