openapi: 3.1.0

info:
  title: Packet header pattern models
  version: ^0.0.0

components:
  schemas:
    Flow.Pattern:
      description: >-
        A container for packet header field patterns.
      type: object
      required: [choice]
      properties:
        choice:
          type: string
          enum: [value, value_list, increment, decrement]
        value:
          oneOf:
            - type: string
            - type: number
        value_list:
          type: array
          items:
            oneOf:
              - type: string
              - type: number
        increment:
          $ref: "#/components/schemas/Flow.Counter"
        decrement:
          $ref: "#/components/schemas/Flow.Counter"
        metric_group:
          description: >-
            A unique name is used to indicate to the system that the field may 
            extend the metric row key and create an aggregate metric row for 
            every unique value.
            To have metric group columns appear in the flow metric rows the flow 
            metric request allows for the metric_group value to be specified
            as part of the request.
          type: string

    Flow.Counter:
      description: >-
        A counter pattern that can increment or decrement.
      type: object
      properties:
        start:
          description: >-
            The value at which the pattern will start.
          oneOf:
            - type: string
            - type: number
        step:
          description: >-
            The value at which the pattern will increment or decrement by.
          oneOf:
            - type: string
            - type: number
        count:
          description: >-
            The number of values in the pattern.
          type: number

