openapi: 3.1.0

info:
  title: Pfc Pause packet header model
  version: ^0.0.0

components:
  schemas:
    Flow.PfcPause:
      description: >-
        IEEE 802.1Qbb PFC Pause packet header.
        - dst: 01:80:C2:00:00:01 48bits
        - src: 48bits 
        - ether_type: 0x8808 16bits
        - control_op_code: 0x0101 16bits
        - class_enable_vector: 16bits
        - pause_class_0: 0x0000 16bits
        - pause_class_1: 0x0000 16bits
        - pause_class_2: 0x0000 16bits
        - pause_class_3: 0x0000 16bits
        - pause_class_4: 0x0000 16bits
        - pause_class_5: 0x0000 16bits
        - pause_class_6: 0x0000 16bits
        - pause_class_7: 0x0000 16bits
      type: object
      properties:
        dst:
          x-pattern:
            description: >-
              Destination MAC address
            format: hex
            length: 48
            default: '000000000000'
            features: [count, metric_group]
        src:
          x-pattern:
            description: >-
              Source MAC address
            format: hex
            length: 48
            default: '000000000000'
            features: [count, metric_group]
        ether_type:
          x-pattern:
            description: >-
              Ethernet type
            format: hex
            length: 16
            default: '8808'
            features: [count, metric_group]
        control_op_code:
          x-pattern:
            description: >-
              Control operation code
            format: hex
            length: 16
            default: '0101'
            features: [count, metric_group]
        class_enable_vector:
          x-pattern:
            description: >-
              Destination
            format: hex
            length: 16
            default: 0
            features: [count, metric_group]
        pause_class_0:
          x-pattern:
            description: >-
              Pause class 0
            format: hex
            length: 16
            default: '0000'
            features: [count, metric_group]
        pause_class_1:
          x-pattern:
            description: >-
              Pause class 1
            format: hex
            length: 16
            default: '0000'
            features: [count, metric_group]
        pause_class_2:
          x-pattern:
            description: >-
              Pause class 2
            format: hex
            length: 16
            default: '0000'
            features: [count, metric_group]
        pause_class_3:
          x-pattern:
            description: >-
              Pause class 3
            format: hex
            length: 16
            default: '0000'
            features: [count, metric_group]
        pause_class_4:
          x-pattern:
            description: >-
              Pause class 4
            format: hex
            length: 16
            default: '0000'
            features: [count, metric_group]
        pause_class_5:
          x-pattern:
            description: >-
              Pause class 5
            format: hex
            length: 16
            default: '0000'
            features: [count, metric_group]
        pause_class_6:
          x-pattern:
            description: >-
              Pause class 6
            format: hex
            length: 16
            default: '0000'
            features: [count, metric_group]
        pause_class_7:
          x-pattern:
            description: >-
              Pause class 7
            format: hex
            length: 16
            default: '0000'
            features: [count, metric_group]


    
