openapi: 3.1.0

info:
  title: PPP traffic packet header
  version: ^0.0.0

components:
  schemas:
    Flow.Ppp:
      description: PPP packet header
      type: object
      properties:
        address:
          description: >-
            PPP address field.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        control:
          description: >-
            PPP control field.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        protocol_type:
          description: >-
            PPP protocol field.
            Indicates the protocol type of the encapsulated payload.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'