openapi: 3.1.0

info:
  title: Vxlan traffic packet header
  version: ^0.0.0

components:
  schemas:
    Flow.Vxlan:
      description: Vxlan packet header
      type: object
      properties:
        flags:
          description: >-
            RRRRIRRR
            Where the I flag MUST be set to 1 for a valid vxlan network id (VNI).  
            The other 7 bits (designated "R") are reserved fields and MUST be 
            set to zero on transmission and ignored on receipt.
            8 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        reserved0:
          description: >-
            Set to 0.
            24 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        vni:
          description: >-
            Vxlan network id.
            24 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
        reserved1:
          description: >-
            Set to 0.
            8 bits.
          $ref: './patterns.yaml#/components/schemas/Flow.Pattern'
