openapi: 3.1.0

info:
  title: Emulated bgpv4 protocol model
  version: ^0.0.0

components:
  schemas:
    Device.Bgpv4:
      x-status: under-review
      x-include: '../common/common.yaml#/components/schemas/Named.Object'
      description: >-
        Emulated BGPv4 router and routes
      type: object
      properties:
        router_id:
          description: >-
            specifies BGP router identifier. It must be the string representation of an IPv4 address 
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        as_number:
          description: >-
            Autonomous system (AS) number of 4 byte
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        as_type:
          description: >-
            The type of BGP autonomous system.
            External BGP (EBGP) is used for BGP links between two or more
            autonomous systems.
            Internal BGP (IBGP) is used within a single autonomous system.
          type: string
          enum: [ibgp, ebgp]
        hold_time_interval:
          description: >-
            Number of seconds the sender proposes for the value of the Hold Timer
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        keep_alive_interval:
          description: >-
            Number of seconds between transmissions of Keep Alive messages by router
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        dut_ipv4_address:
          description: >-
            IPv4 address of the BGP peer for the session
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        dut_as_number:
          description: >-
            Autonomous system (AS) number of the BGP peer router (DUT)
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        ipv4:
          description: >-
            The ipv4 stack that the bgp4 protocol is implemented over.
          $ref: './ipv4.yaml#/components/schemas/Device.Container.Ipv4'
        bgpv4_route_ranges:
          description: >-
            Emulated bgpv4 route ranges
          type: array
          items:
            $ref: '#/components/schemas/Device.Bgpv4RouteRange'
        bgpv6_route_ranges:
          description: >-
            Emulated bgpv6 route ranges
          type: array
          items:
            $ref: '#/components/schemas/Device.Bgpv6RouteRange'

    Device.Bgpv4RouteRange:
      x-include: '../common/common.yaml#/components/schemas/Named.Object'
      description: >-
        Emulated bgpv4 route range
      type: object
      properties:
        route_count_per_device:
          description: >-
            The number of routes per device.
          type: integer
          minimum: 1
          default: 1
        address:
          description: >-
            The network address of the first network
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        prefix:
          description: >-
            Ipv4 prefix length with minimum value is 0 to maximum value is 32
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        as_path:
          description: >-
            Autonomous Systems (AS) numbers that a route passes through to reach the destination
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        next_hop_address:
          description: >-
            IP Address of next router to forward a packet to its final destination
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        community:
          description: >-
            BGP communities provide additional capability for tagging routes and for modifying BGP routing policy on upstream and downstream routers
            BGP community is a 32-bit number which broken into 16-bit As and 16-bit custom value
            Please specify those two values in this string format 65000:100
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'

    Device.Bgpv6RouteRange:
      x-include: '../common/common.yaml#/components/schemas/Named.Object'
      description: >-
        Emulated bgpv6 route range
      type: object
      properties:
        route_count_per_device:
          description: >-
            The number of routes per device.
          type: integer
          minimum: 1
          default: 1
        address:
          description: >-
            The network address of the first network
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        prefix:
          description: >-
            Ipv6 prefix length with minimum value is 0 to maximum value is 128
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        as_path:
          description: >-
            Autonomous Systems (AS) numbers that a route passes through to reach the destination
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        next_hop_address:
          description: >-
            IP Address of next router to forward a packet to its final destination
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        community:
          description: >-
            BGP communities provide additional capability for tagging routes and for modifying BGP routing policy on upstream and downstream routers
            BGP community is a 32-bit number which broken into 16-bit As and 16-bit custom value
            Please specify those two values in this string format 65000:100
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
