openapi: 3.1.0

info:
  title: Emulated device model
  version: ^0.0.0

components:
  schemas:
    Device.Device:
      description: >-
        An abstract container for emulated protocol devices.
        This can grow to accomodate other top level emulated protocols such 
        as ipv4Loopback, ipv6Loopback etc.
      type: object
      required: [name, choice]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        port_name: 
          description: >-
            The name of a port that will host the emulated device stack.
          type: string
          x-constraint: '#/components/schemas/Port.Port.properties.name'
        choice:
          description: >-
            The type of top level emulated protocol device. 
          type: string
          enum: [ethernet]
        ethernet:
          $ref: './ethernet.yaml#/components/schemas/Device.Ethernet'
