openapi: 3.1.0

info:
  title: Emulated device model
  version: ^0.0.0

components:
  schemas:
    Device:
      description: >-
        An abstract container for emulated protocol devices.
      type: object
      required: [name, choice]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        choice:
          description: >-
            The type of emulated protocol device. 
          type: string
          enum: [ethernet, vlan, ipv4, ipv6, bgpv4]
        ethernet:
          $ref: './ethernet.yaml#/components/schemas/Device.Ethernet'
        vlan:
          $ref: './ethernet.yaml#/components/schemas/Device.Ethernet'
        ipv4:
          $ref: './ethernet.yaml#/components/schemas/Device.Ethernet'
        ipv6:
          $ref: './ethernet.yaml#/components/schemas/Device.Ethernet'
        bgpv4:
          $ref: './ethernet.yaml#/components/schemas/Device.Ethernet'
