openapi: 3.1.0

info:
  title: Emulated ethernet protocol model
  version: ^0.0.0

components:
  schemas:
    Device.Ethernet:
      x-include: 
      - '../common/common.yaml#/components/schemas/Named.Object'
      description: >-
        Emulated ethernet protocol.
      type: object
      properties:
        mac:
          description: >-
            Media access control address (MAC)
          x-pattern:
            format: hex
            length: 48
            default: 000000000000
        mtu:
          description: >-
            Maximum transmission unit.
          x-pattern:
            format: integer
            length: 32
            default: 1500
        vlans:
          description: >-
            List of vlans
          type: array
          items:
            $ref: './vlan.yaml#/components/schemas/Device.Vlan'
        ipv4:
          $ref: './ipv4.yaml#/components/schemas/Device.Ipv4' 
        ipv6:
          $ref: './ipv6.yaml#/components/schemas/Device.Ipv6' 

      