openapi: 3.1.0

info:
  title: Emulated ethernet protocol model
  version: ^0.0.0

components:
  schemas:
    Device.Ethernet:
      description: >-
        Emulated ethernet protocol
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        mac:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        mtu:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        vlans:
          description: >-
            List of vlans
          type: array
          items:
            $ref: './vlan.yaml#/components/schemas/Device.Vlan'
        ipv4:
          $ref: './ipv4.yaml#/components/schemas/Device.Ipv4'
        ipv6:
          $ref: './ipv6.yaml#/components/schemas/Device.Ipv6'
    

      