openapi: 3.1.0

info:
  title: Emulated ethernet protocol model
  version: ^0.0.0

components:
  schemas:
    Device.Ethernet:
      description: >-
        Emulated ethernet protocol
      type: object
      required: [name]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        mac:
          description: >-
            Media access control address (MAC) is a 48bit identifier
            for use as a network address.
            The value can be an int or a hex string with or without spaces or 
            colons separating each byte.
            The min value is 0 or '00:00:00:00:00:00'.
            The max value is 281474976710655 or 'FF:FF:FF:FF:FF:FF'.
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        mtu:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        vlans:
          description: >-
            List of vlans
          type: array
          items:
            $ref: './vlan.yaml#/components/schemas/Device.Vlan'
        ipv4:
          $ref: './ipv4.yaml#/components/schemas/Device.Ipv4'
        ipv6:
          $ref: './ipv6.yaml#/components/schemas/Device.Ipv6'
    

      