openapi: 3.1.0

components:
  schemas:
    Device.Ipv4:
      x-include: '../common/common.yaml#/components/schemas/Named.Object'
      description: >-
        Emulated ipv4 protocol
      type: object
      properties:
        address:
          description: >-
            The ipv4 address.
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        gateway:
          description: >-
            The ipv4 address of the gateway.
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        prefix:
          description: >-
            The prefix of the ipv4 address.
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
  
    Device.Container.Ipv4:
      x-include: '#/components/schemas/Device.Ipv4'
      properties:
        ethernet:
          $ref: './ethernet.yaml#/components/schemas/Device.Ethernet'
