openapi: 3.1.0

info:
  title: Emulated ipv6 protocol model
  version: ^0.0.0

components:
  schemas:
    Device.Ipv6:
      x-include: '../common/common.yaml#/components/schemas/Named.Object'
      description: >-
        Emulated ipv6 protocol
      type: object
      properties:
        address:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        gateway:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        prefix:
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        ethernet:
          $ref: './ethernet.yaml#/components/schemas/Device.Ethernet'
      