openapi: 3.1.0

info:
  title: Emulated device property pattern models
  version: 1.0.0

components:
  schemas:
    Device.Pattern:
      description: >-
        A container for emulated device property patterns.
      type: object
      required: [choice]
      properties:
        choice: 
          type: string
          enum: [fixed, list, counter, random]
        fixed:
          type: string
        list:
          type: array
          items:
            type: string
        counter:
          $ref: '#/components/schemas/Device.Counter'
        random:
          $ref: '#/components/schemas/Device.Random'

    Device.Counter:
      description: >-
        An incrementing pattern.
      type: object
      properties:
        start:
          type: string
        step:
          type: string
        up:
          type: boolean
          default: true
    
    Device.Decrement:
      description: >-
        A decrementing pattern.
      type: object
      properties:
        start:
          type: string
        step:
          type: string

    Device.Random:
      description: >-
        A repeatable random range pattern.
      type: object
      properties:
        min:
          type: string
        max:
          type: string
        step: 
          type: number
        seed:
          type: string

