openapi: 3.1.0

info:
  title: Emulated vlan protocol model
  version: ^0.0.0

components:
  schemas:
    Device.Vlan:
      x-include: '../common/common.yaml#/components/schemas/Named.Object'
      description: >-
        Emulated vlan protocol
      type: object
      x-constants:
        tpid_8100: 8100
        tpid_88a8: 88a8
        tpid_9100: 9100
        tpid_9200: 9200
        tpid_9300: 9300
      properties:
        tpid:
          description: >-
            Vlan tag protocol identifier.
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        priority:
          description: >-
            Vlan priority.
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
        id:
          description: >-
            Vlan id.
          $ref: './patterns.yaml#/components/schemas/Device.Pattern'
    