openapi: 3.1.0

info:
  title: Link aggregation (LAG) models
  version: ^0.0.0

components:
  schemas:
    Lag:
      description: >-
        A container for LAG settings.
      type: object
      required: [name, protocol]
      properties:
        name: '../common/common.yaml#/components/x-inline/UniqueName'
        port_names:
          description: >- 
            A list of unique names of port objects that will be part of the 
            same lag. 
          type: array
          items:
            type: string
            x-constraint:
            - '/components/schemas/Port/properties/name'
        protocol:
          description: >-
            Static lag or LACP protocol settings.
          $ref: '#/components/schemas/Lag.Protocol'
        ethernet:
          description: >-
            Per port ethernet and vlan settings.
          $ref: '../device/ethernet.yaml#/components/schemas/Device.Ethernet'
        devices:
          description: >-
            Emulated protocol devices.
          type: array
          items:
            $ref: '../device/device.yaml#/components/schemas/Device'

    Lag.Protocol:
      type: object
      required: [choice]
      properties:
        choice:
          description: >-
            The type of lag protocol.
          type: string
          enum: [lacp, static]
        lacp:
          $ref: '#/components/schemas/Lag.Lacp'
        static:
          $ref: '#/components/schemas/Lag.Static'

    Lag.Static:
      type: object
      properties:
        lag_id:
          $ref: '../device/patterns.yaml#/components/schemas/Device.Pattern'

    Lag.Lacp:
      type: object
      properties:
        actor_key:
          $ref: '../device/patterns.yaml#/components/schemas/Device.Pattern'
        actor_port_number:
          $ref: '../device/patterns.yaml#/components/schemas/Device.Pattern'
        actor_port_priority:
          $ref: '../device/patterns.yaml#/components/schemas/Device.Pattern'
        actor_system_id:
          $ref: '../device/patterns.yaml#/components/schemas/Device.Pattern'
        actor_system_priority:
          $ref: '../device/patterns.yaml#/components/schemas/Device.Pattern'

