openapi: 3.1.0

info:
  title: Link aggregation (LAG) models
  version: ^0.0.0

components:
  schemas:
    Lag:
      x-include: 
      - '../common/common.yaml#/components/schemas/Named.Object'
      description: >-
        A container for LAG settings.
      type: object
      required: [protocol]
      properties:
        port_names:
          description: >- 
            A list of unique names of port objects that will be part of the 
            same lag. 
            The value of the port_names property is the count for any child 
            property in this hierarchy that is a container for a device pattern.
          type: array
          items:
            type: string
            x-constraint:
            - '/components/schemas/Port/properties/name'
        protocol:
          description: >-
            Static lag or LACP protocol settings.
          $ref: '#/components/schemas/Lag.Protocol'
        ethernet:
          description: >-
            Per port ethernet and vlan settings.
          $ref: '../device/ethernet.yaml#/components/schemas/Device.Ethernet'

    Lag.Protocol:
      type: object
      required: [choice]
      properties:
        choice:
          description: >-
            The type of lag protocol.
          type: string
          enum: [lacp, static]
        lacp:
          description: >-
            The container for link aggregation control protocol settings.
          $ref: '#/components/schemas/Lag.Lacp'
        static:
          description: >-
            The container for link aggregation static protocol settings.
          $ref: '#/components/schemas/Lag.Static'

    Lag.Static:
      type: object
      properties:
        lag_id:
          description: >-
            The static lag id.
          $ref: '../device/patterns.yaml#/components/schemas/Device.Pattern'

    Lag.Lacp:
      type: object
      properties:
        actor_key:
          description: >-
            The actor key.
          $ref: '../device/patterns.yaml#/components/schemas/Device.Pattern'
        actor_port_number:
          description: >-
            The actor port number.
          $ref: '../device/patterns.yaml#/components/schemas/Device.Pattern'
        actor_port_priority:
          description: >-
            The actor port priority.
          $ref: '../device/patterns.yaml#/components/schemas/Device.Pattern'
        actor_system_id:
          description: >-
            The actor system id.
          $ref: '../device/patterns.yaml#/components/schemas/Device.Pattern'
        actor_system_priority:
          description: >-
            The actor system priority.
          $ref: '../device/patterns.yaml#/components/schemas/Device.Pattern'

