components:
  schemas:
    CertConfig:
      properties:
        certificatefile:
          $ref: ../params/params.yaml#/components/schemas/Params
          default: method(GetDefaultCertificateFile)
          description: The certificate file of the TLS profile.
          x-field-uid: 1
        dhfile:
          $ref: ../params/params.yaml#/components/schemas/Params
          default: method(GetDefaultDhFile)
          x-field-uid: 2
        get_sni_conflicts:
          items:
            format: byte
            type: string
          type: array
          x-field-uid: 3
        id:
          $ref: ../id/id.yaml#/components/schemas/ID
          x-field-uid: 4
        isplaylist:
          default: false
          type: boolean
          x-field-uid: 5
        keyfile:
          $ref: ../params/params.yaml#/components/schemas/Params
          default: method(GetDefaultKeyFile)
          description: The key file of the TLS profile.
          x-field-uid: 6
        keyfilepassword:
          default: appsec
          description: The key file password of the TLS profile.
          type: string
          x-field-uid: 7
        links:
          items:
            $ref: ../apilink/apilink.yaml#/components/schemas/APILink
          type: array
          x-field-uid: 8
        playlistcolumnname:
          type: string
          x-field-uid: 9
        playlistfilename:
          type: string
          x-field-uid: 10
        resolve_sni_conflicts:
          items:
            $ref: ../conflict/conflict.yaml#/components/schemas/Conflict
          type: array
          x-field-uid: 11
        snihostname:
          description: 'The SNI hostname associated with the certificate. (default:
            generic.keysight.io).'
          type: string
          x-field-uid: 12
      required:
      - snihostname
      - id
      type: object
