components:
  schemas:
    PortSettings:
      properties:
        automatic:
          type: boolean
          x-field-uid: 1
        automaticdestinationport:
          type: boolean
          x-field-uid: 2
        automaticforwardproxyport:
          type: boolean
          x-field-uid: 3
        destinationport:
          format: int32
          type: integer
          x-field-uid: 4
        effectiveports:
          $ref: ../effectiveports/effectiveports.yaml#/components/schemas/EffectivePorts
          x-field-uid: 5
        forwardproxyport:
          format: int32
          type: integer
          x-field-uid: 6
        links:
          items:
            $ref: ../apilink/apilink.yaml#/components/schemas/APILink
          type: array
          x-field-uid: 9
        readonly:
          description: If true, the port can't be selected by the user
          type: boolean
          x-field-uid: 7
        serverlistenport:
          format: int32
          type: integer
          x-field-uid: 8
      required:
      - automatic
      - destinationport
      - automaticdestinationport
      - serverlistenport
      - automaticforwardproxyport
      - forwardproxyport
      type: object
