components:
  schemas:
    ESPOverUDPSettings:
      properties:
        links:
          items:
            $ref: ../apilink/apilink.yaml#/components/schemas/APILink
          type: array
          x-field-uid: 2
        udpprofile:
          $ref: ../udpprofile/udpprofile.yaml#/components/schemas/UdpProfile
          x-field-uid: 1
      type: object
