components:
  schemas:
    AuthenticationSettings:
      properties:
        authmethod:
          default: PRE-SHARED-KEY
          type: string
          x-enum:
            CERTIFICATES:
              x-field-uid: 2
            v10:
              x-field-uid: 1
          x-field-uid: 1
        certificatefile:
          $ref: ../params/params.yaml#/components/schemas/Params
          default: method(GetDefaultCertificateFile)
          description: The authentication certificate file of the IPsec tunnel(s).
          x-field-uid: 2
        keyfile:
          $ref: ../params/params.yaml#/components/schemas/Params
          default: method(GetDefaultKeyFile)
          description: The authentication key file of the IPsec tunnel(s).
          x-field-uid: 3
        keyfilepassword:
          description: The key file password of the IPsec authentication.
          type: string
          x-field-uid: 4
        links:
          items:
            $ref: ../apilink/apilink.yaml#/components/schemas/APILink
          type: array
          x-field-uid: 6
        sharedkey:
          default: ipsec
          type: string
          x-field-uid: 5
      type: object
