openapi: 3.0.3

info:
  title: Open Traffic Generator API
  description: >-
    The open traffic generator API
  version: 0.0.11
  contact:
    name: Open Traffic Generator Project Team
    email: andy.balogh@keysight.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers: 
  - url: /

paths: 
  /config:
    description: >-
      Configuration API
    post:
      tags:
        - Config
      operationId: set_config
      description: >-
        Creates new or updates existing traffic generator configuration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../config/config.yaml#/components/schemas/Config'
      responses:
        '200':
          description: >-
            A list of configuration validation errors.
            An empty list indicates there are no errors.
          content:
            application/json:
              schema:
                $ref: '../result/result.yaml#/components/schemas/Result.Errors'
    get:
      tags:
        - Config
      operationId: get_config
      description: >-
        Returns traffic generator configuration.
      responses:
        '200':
          description: >-
            The most recent traffic generator configuration.
            An empty configuration indicates that configuration does not exist.
          content:
            application/json:
              schema:
                $ref: '../config/config.yaml#/components/schemas/Config'

  /control/action:
    description: >-
      Control action API
    post:
      tags:
        - Control
      operationId: set_control_action
      description: >-
        Applies a list of control actions on intended traffic generator resources
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../control/control.yaml#/components/schemas/Control.Action'
      responses:
        '202':
          description: >-
            The request for intended control actions have been accepted and is in progress.
            The response body will contain status url which will provide subsequent progress status.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_url:
                    type: string

  /control/status:
    description: >-
      Control status API
    get:
      tags:
        - Control
      operationId: get_control_status
      description: >-
        Returns status for all supported control actions.
      responses:
        '200':
          description: >-
            A key-value pair of each supported action and its corresponding status.
          content:
            application/json:
              schema:
                $ref: '../control/control.yaml#/components/schemas/Control.Status'

  /results/capabilities:
    description: >-
      Capability results API
    post:
      tags:
        - Results
      operationId: get_capability_results
      responses:
        '200':
          description: >-
            Capability results response from the traffic generator
          content:
            application/json:
              schema:
                $ref: '../result/result.yaml#/components/schemas/Result.Capability'

  /results/port:
    description: >-
      Port results API
    post:
      tags:
        - Results
      operationId: get_port_results
      requestBody:
        description: >-
          Port results request to the traffic generator.
        required: true
        content:
          application/json:
            schema:
              $ref: '../result/port.yaml#/components/schemas/Result.PortRequest'
      responses:
        '200':
          description: >-
            Port results response from the traffic generator
          content:
            application/json:
              schema:
                $ref: '../result/result.yaml#/components/schemas/Result.Table'

  /results/capture:
    description: >-
      Capture results API
    post:
      tags:
        - Results
      operationId: get_capture_results
      requestBody:
        description: >-
          Capture results request to the traffic generator.
        required: true
        content:
          application/json:
            schema:
              $ref: '../result/capture.yaml#/components/schemas/Result.CaptureRequest'
      responses:
        '200':
          description: >-
            Capture results response from the traffic generator. 
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  /results/flow:
    description: >-
      Flow results API
    post:
      tags:
        - Results
      operationId: get_flow_results
      requestBody:
        description: >-
          Flow results request to the traffic generator.
        required: true
        content:
          application/json:
            schema:
              $ref: '../result/flow.yaml#/components/schemas/Result.FlowRequest'
      responses:
        '200':
          description: >-
            Flow results response from the traffic generator
          content:
            application/json:
              schema:
                $ref: '../result/result.yaml#/components/schemas/Result.Table'


