openapi: 3.0.3

info:
  title: Open Traffic Generator API
  description: >-
    The open traffic generator API
  version: 0.0.11
  contact:
    name: Open Traffic Generator Project Team
    email: andy.balogh@keysight.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers: 
  - url: /

paths: 
  /config:
    description: >-
      Configuration API
    post:
      tags:
        - Config
      operationId: set_config
      description: >-
        Sets the configuration on the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../config/config.yaml#/components/schemas/Config'
      responses:
        '204':
          description: >-
            The operation has successfully completed with no content.
        '202':
          description: >-
            The operation has been accepted and is in progress.
            The response payload will contain two urls
              - one to get the progress of the current operation
                Each subsequent progress request can return one of the following:     
                  - 204 if the operation has successfully 
                  - 202 if the operation is still in progress
                  - 400 if the operation has failed
              - one to cancel the operation. 
          content:
            application/json:
              schema:
                type: object
                properties:
                  progress_url:
                    type: string
                  cancellation_url:
                    type: string
        '400':
          description: >-
            The operation has failed.
            The failure response will be a list errors.
            The operation should not be repeated without modifications.
          content:
            application/json:
              schema:
                $ref: '../result/result.yaml#/components/schemas/Result.Errors'
        '409':
          description: >-
            The request conflicts with an executing request.
          content:
            application/json:
              schema:
                $ref: '../result/result.yaml#/components/schemas/Result.Errors'
          
  /control/port/link:
    description: >-
      Control port link API
    post:
      tags:
        - Control
      operationId: set_port_link
      description: >-
        Sets the port link state on the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../control/control.yaml#/components/schemas/Control.PortLink'
      responses:
        '204':
          description: >-
            No content

  /control/port/capture:
    description: >-
      Control port capture API
    post:
      tags:
        - Control
      operationId: set_port_capture
      description: >-
        Starts a port capture on the traffic generator.
        
        Use the /results/capture API to stop a port capture and get the captured
        results.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../control/control.yaml#/components/schemas/Control.PortCapture'
      responses:
        '204':
          description: >-
            No content

  /control/flow/transmit:
    description: >-
      Control flow transmit API
    post:
      tags:
        - Control
      operationId: set_flow_transmit
      description: >-
        Sets the flow transmit state on the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../control/control.yaml#/components/schemas/Control.FlowTransmit'
      responses:
        '204':
          description: >-
            No content

  /results/capabilities:
    description: >-
      Capability results API
    post:
      tags:
        - Results
      operationId: get_capability_results
      responses:
        '200':
          description: >-
            Capability results response from the traffic generator
          content:
            application/json:
              schema:
                $ref: '../result/result.yaml#/components/schemas/Result.Capability'

  /results/port:
    description: >-
      Port results API
    post:
      tags:
        - Results
      operationId: get_port_results
      requestBody:
        description: >-
          Port results request to the traffic generator.
        required: true
        content:
          application/json:
            schema:
              $ref: '../result/port.yaml#/components/schemas/Result.PortRequest'
      responses:
        '200':
          description: >-
            Port results response from the traffic generator
          content:
            application/json:
              schema:
                $ref: '../result/result.yaml#/components/schemas/Result.Table'

  /results/capture:
    description: >-
      Capture results API
    post:
      tags:
        - Results
      operationId: get_capture_results
      requestBody:
        description: >-
          Capture results request to the traffic generator.
        required: true
        content:
          application/json:
            schema:
              $ref: '../result/capture.yaml#/components/schemas/Result.CaptureRequest'
      responses:
        '200':
          description: >-
            Capture results response from the traffic generator. 
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  /results/flow:
    description: >-
      Flow results API
    post:
      tags:
        - Results
      operationId: get_flow_results
      requestBody:
        description: >-
          Flow results request to the traffic generator.
        required: true
        content:
          application/json:
            schema:
              $ref: '../result/flow.yaml#/components/schemas/Result.FlowRequest'
      responses:
        '200':
          description: >-
            Flow results response from the traffic generator
          content:
            application/json:
              schema:
                $ref: '../result/result.yaml#/components/schemas/Result.Table'


