openapi: 3.0.3

info:
  title: Open Traffic Generator API
  description: >-
    The open traffic generator API
  version: 0.1.1
  contact:
    name: Open Traffic Generator Project Team
    email: andy.balogh@keysight.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers: 
  - url: /

paths: 
  /config:
    post:
      tags: [Configuration]
      operationId: set_config
      description: >-
        Sets configuration resources on the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../config/config.yaml#/components/schemas/Config'
      responses:
        '200':
          $ref: '../result/request.yaml#/components/responses/Success'
        '409':
          $ref: '../result/request.yaml#/components/responses/Conflict'
        '590':
          $ref: '../result/request.yaml#/components/responses/Fail'
    patch:
      tags: [Configuration]
      operationId: update_config
      description: >-
        Updates configuration resources on the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../config/config.yaml#/components/schemas/Config'
      responses:
        '200':
          $ref: '../result/request.yaml#/components/responses/Success'
        '409':
          $ref: '../result/request.yaml#/components/responses/Conflict'
        '590':
          $ref: '../result/request.yaml#/components/responses/Fail'
    get:
      tags: [Configuration]
      operationId: get_config
      responses:
        '200':
          description: >-
            Config response from the traffic generator
          content:
            application/json:
              schema:
                $ref: '../config/config.yaml#/components/schemas/Config'

  /control/transmit:
    post:
      tags: [Control]
      operationId: set_transmit_state
      description: >-
        Updates the state of configuration resources on the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../control/control.yaml#/components/schemas/Transmit.State'
      responses:
        '200':
          $ref: '../result/request.yaml#/components/responses/Success'
        '409':
          $ref: '../result/request.yaml#/components/responses/Conflict'
        '590':
          $ref: '../result/request.yaml#/components/responses/Fail'

  /control/link:
    post:
      tags: [Control]
      operationId: set_link_state
      description: >-
        Updates the state of configuration resources on the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../control/control.yaml#/components/schemas/Link.State'
      responses:
        '200':
          $ref: '../result/request.yaml#/components/responses/Success'
        '409':
          $ref: '../result/request.yaml#/components/responses/Conflict'
        '590':
          $ref: '../result/request.yaml#/components/responses/Fail'

  /control/capture:
    post:
      tags: [Control]
      operationId: set_capture_state
      description: >-
        Updates the state of configuration resources on the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../control/control.yaml#/components/schemas/Capture.State'
      responses:
        '200':
          $ref: '../result/request.yaml#/components/responses/Success'
        '409':
          $ref: '../result/request.yaml#/components/responses/Conflict'
        '590':
          $ref: '../result/request.yaml#/components/responses/Fail'

  /results/state:
    post:
      tags: [Results]
      operationId: get_state_metrics
      responses:
        '200':
          description: List of states
          content:
            application/json:
              schema:
                $ref: '../result/state.yaml#/components/schemas/State.Metrics'

  /results/capabilities:
    description: >-
      Capability results API
    post:
      tags: [Results]
      operationId: get_capabilities
      responses:
        '200':
          description: >-
            Capability results response from the traffic generator
          content:
            application/json:
              schema:
                $ref: '../result/capability.yaml#/components/schemas/Capabilities'

  /results/port:
    description: >-
      Port results API
    post:
      tags: [Results]
      operationId: get_port_metrics
      requestBody:
        description: >-
          Port results request to the traffic generator.
        required: true
        content:
          application/json:
            schema:
              $ref: '../result/port.yaml#/components/schemas/Port.Metrics.Request'
      responses:
        '200':
          description: >-
            Port results response from the traffic generator
          content:
            application/json:
              schema:
                $ref: '../result/port.yaml#/components/schemas/Port.Metrics'

  /results/capture:
    description: >-
      Capture results API
    post:
      tags: [Results]
      operationId: get_capture
      requestBody:
        description: >-
          Capture results request to the traffic generator.
        required: true
        content:
          application/json:
            schema:
              $ref: '../result/capture.yaml#/components/schemas/Capture.Request'
      responses:
        '200':
          description: >-
            Capture results response from the traffic generator. 
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  /results/flow:
    description: >-
      Flow results API
    post:
      tags: [Results]
      operationId: get_flow_metrics
      requestBody:
        description: >-
          Flow results request to the traffic generator.
        required: true
        content:
          application/json:
            schema:
              $ref: '../result/flow.yaml#/components/schemas/Flow.Metrics.Request'
      responses:
        '200':
          description: >-
            Flow results response from the traffic generator
          content:
            application/json:
              schema:
                $ref: '../result/flow.yaml#/components/schemas/Flow.Metrics'

  /results/bgpv4:
    description: >-
      BGP results API
    post:
      tags: [Results]
      operationId: get_bgpv4_metrics
      requestBody:
        description: >-
          The request to retrieve BGP Router statistics and learned routing information.
        required: true
        content:
          application/json:
            schema:
              $ref: '../result/bgpv4.yaml#/components/schemas/Bgpv4.Metrics.Request'
      responses:
        '200':
          description: >-
            BGP Router statistics and learned routing information
          content:
            application/json:
              schema:
                $ref: '../result/bgpv4.yaml#/components/schemas/Bgpv4.Metrics'
