openapi: 3.0.3

info:
  title: Open Traffic Generator API
  description: >-
    The open traffic generator API
  version: 0.1.13
  contact:
    name: Open Traffic Generator Project Team
    email: andy.balogh@keysight.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  x-extensions: 
    - x-pattern: '../flow/packet-header/patterns.yaml#/components/schemas/Flow.Pattern'
      format: Valid formats of string value, values, start, step are ipv4, ipv6, hex, mac, integer, number
      default: Default value of Flow.Pattern/properties/value
    - x-status: >-
        current | under-review | deprecated | obsolete
        - If no status is specified, the default is "current".
        - the `x-status` keyword takes as an argument one of the strings
        "current", "deprecated", or "obsolete", "under-review.
        - "current" means that the definition is current and valid.
        - "deprecated" indicates an obsolete definition, but it permits new/
          continued implementation in order to foster interoperability with
          older/existing implementations.
        - "obsolete" means the definition is obsolete and SHOULD NOT be
          implemented and/or can be removed from implementations.
          
        Example Usage:
          components:
            schemas:
              Device.BgpAsPath:
                x-status: under-review
                type:object

servers: 
  - url: /

paths: 
  /config:
    post:
      tags: [Configuration]
      operationId: set_config
      description: >-
        Sets configuration resources on the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../config/config.yaml#/components/schemas/Config'
      responses:
        '200':
          $ref: '../result/request.yaml#/components/responses/Success'
        '409':
          $ref: '../result/request.yaml#/components/responses/Conflict'
        '590':
          $ref: '../result/request.yaml#/components/responses/Fail'
    patch:
      tags: [Configuration]
      operationId: update_config
      description: >-
        Updates configuration resources on the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../config/config.yaml#/components/schemas/Config'
      responses:
        '200':
          $ref: '../result/request.yaml#/components/responses/Success'
        '409':
          $ref: '../result/request.yaml#/components/responses/Conflict'
        '590':
          $ref: '../result/request.yaml#/components/responses/Fail'
    get:
      tags: [Configuration]
      operationId: get_config
      responses:
        '200':
          description: >-
            Config response from the traffic generator
          content:
            application/json:
              schema:
                $ref: '../config/config.yaml#/components/schemas/Config'

  /control/transmit:
    post:
      tags: [Control]
      operationId: set_transmit_state
      description: >-
        Updates the state of configuration resources on the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../control/control.yaml#/components/schemas/Transmit.State'
      responses:
        '200':
          $ref: '../result/request.yaml#/components/responses/Success'
        '409':
          $ref: '../result/request.yaml#/components/responses/Conflict'
        '590':
          $ref: '../result/request.yaml#/components/responses/Fail'

  /control/link:
    post:
      tags: [Control]
      operationId: set_link_state
      description: >-
        Updates the state of configuration resources on the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../control/control.yaml#/components/schemas/Link.State'
      responses:
        '200':
          $ref: '../result/request.yaml#/components/responses/Success'
        '409':
          $ref: '../result/request.yaml#/components/responses/Conflict'
        '590':
          $ref: '../result/request.yaml#/components/responses/Fail'

  /control/capture:
    post:
      tags: [Control]
      operationId: set_capture_state
      description: >-
        Updates the state of configuration resources on the traffic generator.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../control/control.yaml#/components/schemas/Capture.State'
      responses:
        '200':
          $ref: '../result/request.yaml#/components/responses/Success'
        '409':
          $ref: '../result/request.yaml#/components/responses/Conflict'
        '590':
          $ref: '../result/request.yaml#/components/responses/Fail'

  /results/metrics:
    description: >-
      Traffic metrics API
    post:
      tags: [Results]
      operationId: get_metrics
      requestBody:
        description: >-
          Request to traffic generator for metrics of choice
        required: true
        content:
          application/json:
            schema:
              $ref: '../result/metrics.yaml#/components/schemas/Metrics.Request'
      responses:
        '200':
          description: >-
            Response from traffic generator for chosen metrics
          content:
            application/json:
              schema:
                $ref: '../result/metrics.yaml#/components/schemas/Metrics.Response'

  /results/state:
    post:
      tags: [Results]
      operationId: get_state_metrics
      responses:
        '200':
          description: List of states
          content:
            application/json:
              schema:
                $ref: '../result/state.yaml#/components/schemas/State.Metrics'

  /results/capabilities:
    description: >-
      Capability results API
    post:
      tags: [Results]
      operationId: get_capabilities
      responses:
        '200':
          description: >-
            Capability results response from the traffic generator
          content:
            application/json:
              schema:
                $ref: '../result/capability.yaml#/components/schemas/Capabilities'

  /results/capture:
    description: >-
      Capture results API
    post:
      tags: [Results]
      operationId: get_capture
      requestBody:
        description: >-
          Capture results request to the traffic generator.
        required: true
        content:
          application/json:
            schema:
              $ref: '../result/capture.yaml#/components/schemas/Capture.Request'
      responses:
        '200':
          description: >-
            Capture results response from the traffic generator. 
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
