openapi: 3.0.3
info:
  title: Open Traffic Generator API
  description: |-
    Open Traffic Generator API defines a model-driven, vendor-neutral and standard 
    interface for emulating layer 2-7 network devices and generating test traffic.

    Contributions can be made in the following ways:
    - [open an issue](https://github.com/open-traffic-generator/models/issues) in the models repository
    - [fork the models repository](https://github.com/open-traffic-generator/models) and submit a PR
  version: 0.8.7
  contact:
    url: https://github.com/open-traffic-generator/models
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  x-model-guide: https://github.com/open-traffic-generator/models/blob/master/MODEL-GUIDE.md
servers:
- url: /
paths: {}
