openapi: 3.0.3

info:
  title: Open Traffic Generator API
  description: |-
    The Open Traffic Generator API consists of the following features:
    - a common Traffic Generator API
    - an Advanced Metrics API feature (under review)

    Contributions can be made in the following ways:
    - [open an issue](https://github.com/open-traffic-generator/models/issues) in the models repository
    - [fork the models repository](https://github.com/open-traffic-generator/models) and submit a PR
  version: 0.4.0
  contact:
    url: https://github.com/open-traffic-generator/models
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  x-model-guide: https://github.com/open-traffic-generator/models/blob/master/MODEL-GUIDE.md

servers: 
  - url: /

paths: {}
