components:
  schemas:
    AuthSettings:
      properties:
        authmethod:
          $ref: ../authmethodtype/authmethodtype.yaml#/components/schemas/AuthMethodType
          x-field-uid: 1
        authparam:
          $ref: ../params/params.yaml#/components/schemas/Params
          x-field-uid: 2
        certificatefile:
          $ref: ../params/params.yaml#/components/schemas/Params
          description: The authentication certificate file of the VPN tunnel.
          x-field-uid: 3
        keyfile:
          $ref: ../params/params.yaml#/components/schemas/Params
          description: The authentication key file of the VPN tunnel.
          x-field-uid: 4
        keyfilepassword:
          description: The key file password of the TLS VPN authentication.
          type: string
          x-field-uid: 5
        passwords:
          items:
            type: string
          type: array
          x-field-uid: 6
        passwordsparam:
          $ref: ../params/params.yaml#/components/schemas/Params
          x-field-uid: 7
        usernames:
          items:
            type: string
          type: array
          x-field-uid: 8
        usernamesparam:
          $ref: ../params/params.yaml#/components/schemas/Params
          x-field-uid: 9
      type: object
